FROM maven:3.9.11-eclipse-temurin-25 AS build
WORKDIR /app
COPY pom.xml .
RUN mvn -q -DskipTests dependency:go-offline
COPY src ./src
RUN mvn -q -DskipTests compile dependency:copy-dependencies -DoutputDirectory=target/dependency

FROM eclipse-temurin:25-jre
WORKDIR /app
COPY --from=build /app/target/classes ./classes
COPY --from=build /app/target/dependency ./dependency
EXPOSE 8080
ENTRYPOINT ["java", "-cp", "classes:dependency/*", "api.publica.ApiPublicaApp"]
