FROM nginx:1.29-alpine
COPY web-publica/index.html /usr/share/nginx/html/index.html
COPY web-publica/styles.css /usr/share/nginx/html/styles.css
COPY web-publica/app.js /usr/share/nginx/html/app.js
COPY web-publica/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
