package dao;
import java.sql.*; import java.util.*; import negocio.*;
public class TorneoGrupoDAOMySQL implements TorneoGrupoDAO {
 public List<TorneoGrupo> listar(Connection c,long cat){try{List<TorneoGrupo> xs=new ArrayList<>();try(PreparedStatement s=c.prepareStatement("SELECT id,torneo_categoria_id,nombre,orden,capacidad,modo_asignacion,confirmado FROM torneo_grupos WHERE torneo_categoria_id=? ORDER BY orden")){s.setLong(1,cat);try(ResultSet r=s.executeQuery()){while(r.next()){TorneoGrupo g=new TorneoGrupo();g.setId(r.getLong(1));g.setTorneoCategoriaId(r.getLong(2));g.setNombre(r.getString(3));g.setOrden(r.getInt(4));g.setCapacidad(r.getInt(5));g.setModoAsignacion(ModoAsignacionGrupoTorneo.valueOf(r.getString(6)));g.setConfirmado(r.getBoolean(7));g.setIntegrantes(integrantes(c,g.getId()));xs.add(g);}}}return xs;}catch(SQLException e){throw new RuntimeException("No se pudieron listar los grupos.",e);}}
 private List<TorneoGrupoIntegrante> integrantes(Connection c,long gid)throws SQLException{List<TorneoGrupoIntegrante> xs=new ArrayList<>();String q="SELECT tgi.id,tgi.grupo_id,tgi.inscripcion_id,tgi.cabeza_serie,tgi.orden_sorteo,CONCAT(j1.nombre,' ',j1.apellido,' / ',j2.nombre,' ',j2.apellido) pareja FROM torneo_grupo_integrantes tgi JOIN torneo_inscripcion_jugadores j1 ON j1.inscripcion_id=tgi.inscripcion_id AND j1.orden_integrante=1 JOIN torneo_inscripcion_jugadores j2 ON j2.inscripcion_id=tgi.inscripcion_id AND j2.orden_integrante=2 WHERE tgi.grupo_id=? ORDER BY tgi.cabeza_serie DESC,tgi.orden_sorteo,tgi.id";try(PreparedStatement s=c.prepareStatement(q)){s.setLong(1,gid);try(ResultSet r=s.executeQuery()){while(r.next()){TorneoGrupoIntegrante x=new TorneoGrupoIntegrante();x.setId(r.getLong(1));x.setGrupoId(r.getLong(2));x.setInscripcionId(r.getLong(3));x.setCabezaSerie(r.getBoolean(4));x.setOrdenSorteo(r.getInt(5));x.setNombrePareja(r.getString(6));xs.add(x);}}}return xs;}
 public void crearEstructura(Connection c,long cat,int g3,int g4){try{try(PreparedStatement d=c.prepareStatement("DELETE FROM torneo_grupos WHERE torneo_categoria_id=?")){d.setLong(1,cat);d.executeUpdate();}String q="INSERT INTO torneo_grupos(torneo_categoria_id,nombre,orden,capacidad) VALUES(?,?,?,?)";try(PreparedStatement s=c.prepareStatement(q)){int o=1;for(int i=0;i<g3;i++)add(s,cat,o++,3);for(int i=0;i<g4;i++)add(s,cat,o++,4);}}catch(SQLException e){throw new RuntimeException("No se pudo crear la estructura de grupos.",e);}}
 private void add(PreparedStatement s,long cat,int o,int cap)throws SQLException{s.setLong(1,cat);s.setString(2,"Grupo "+letra(o));s.setInt(3,o);s.setInt(4,cap);s.executeUpdate();} private String letra(int o){return o<=26?String.valueOf((char)('A'+o-1)):String.valueOf(o);}
 public void asignar(Connection c,long gid,long iid,boolean cabeza,int orden){try{quitar(c,iid);if(cabeza)try(PreparedStatement x=c.prepareStatement("UPDATE torneo_grupo_integrantes SET cabeza_serie=FALSE WHERE grupo_id=?")){x.setLong(1,gid);x.executeUpdate();}try(PreparedStatement s=c.prepareStatement("INSERT INTO torneo_grupo_integrantes(grupo_id,inscripcion_id,cabeza_serie,orden_sorteo) VALUES(?,?,?,?)")){s.setLong(1,gid);s.setLong(2,iid);s.setBoolean(3,cabeza);s.setInt(4,orden);s.executeUpdate();}}catch(SQLException e){throw new RuntimeException("No se pudo asignar la pareja.",e);}}
 public void quitar(Connection c,long iid){try(PreparedStatement s=c.prepareStatement("DELETE FROM torneo_grupo_integrantes WHERE inscripcion_id=?")){s.setLong(1,iid);s.executeUpdate();}catch(SQLException e){throw new RuntimeException("No se pudo quitar la pareja.",e);}}
 public void limpiarAsignaciones(Connection c,long cat){try(PreparedStatement s=c.prepareStatement("DELETE tgi FROM torneo_grupo_integrantes tgi JOIN torneo_grupos tg ON tg.id=tgi.grupo_id WHERE tg.torneo_categoria_id=?")){s.setLong(1,cat);s.executeUpdate();}catch(SQLException e){throw new RuntimeException("No se pudieron limpiar los grupos.",e);}}
 public void confirmar(Connection c,long cat,ModoAsignacionGrupoTorneo m){try(PreparedStatement s=c.prepareStatement("UPDATE torneo_grupos SET confirmado=TRUE,modo_asignacion=? WHERE torneo_categoria_id=?")){s.setString(1,m.name());s.setLong(2,cat);s.executeUpdate();}catch(SQLException e){throw new RuntimeException("No se pudieron confirmar los grupos.",e);}} }
