package vista.controlador;

import java.awt.Desktop;
import java.io.File;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.NumberFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.TextStyle;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

import javafx.application.Platform;
import javafx.concurrent.Task;
import javafx.fxml.FXML;
import javafx.geometry.Pos;
import javafx.geometry.Side;
import javafx.scene.chart.BarChart;
import javafx.scene.chart.LineChart;
import javafx.scene.chart.NumberAxis;
import javafx.scene.chart.PieChart;
import javafx.scene.chart.XYChart;
import javafx.scene.chart.Chart;
import javafx.scene.control.Button;
import javafx.scene.control.DateCell;
import javafx.scene.control.DatePicker;
import javafx.scene.control.Label;
import javafx.scene.control.ProgressIndicator;
import javafx.scene.control.ScrollPane;
import javafx.scene.control.TableCell;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TableView;
import javafx.scene.control.ToggleButton;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.scene.layout.VBox;
import javafx.stage.FileChooser;
import negocio.CierreCaja;
import negocio.EstadisticasPadel;
import negocio.EstadisticasPadel.DatoGrafico;
import servicio.EstadisticasService;
import servicio.ConfiguracionComplejoService;
import servicio.GuiaEstadisticasPdfService;
import vista.Dialogos;
import vista.Navegacion;
import vista.AyudaEstadisticasDialogo;

public class EstadisticasController {
    // cerrar-estadisticas-estructural-v1
    // cerrar-estadisticas-graficos-v3
    // cerrar-estadisticas-semantica-v4
    private static final DateTimeFormatter FECHA=DateTimeFormatter.ofPattern("dd/MM/yyyy"), FECHA_HORA=DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
    private final EstadisticasService service=new EstadisticasService();
    private final ConfiguracionComplejoService configuracionService=new ConfiguracionComplejoService();
    private final GuiaEstadisticasPdfService guiaPdfService=new GuiaEstadisticasPdfService();
    @FXML private DatePicker fechaDesde,fechaHasta; @FXML private Button botonActualizar; @FXML private ProgressIndicator indicadorCarga; @FXML private Label etiquetaEstado,etiquetaPeriodoComparado;
    @FXML private Label etiquetaTotalReservas,etiquetaEfectivas,etiquetaPendientes,etiquetaConfirmadas,etiquetaCompletadas,etiquetaCanceladas,etiquetaAusencias,etiquetaExpiradas,etiquetaIngresos,etiquetaReembolsado,etiquetaIngresosNetos,etiquetaIngresosManuales,etiquetaEgresosManuales,etiquetaResultadoOperativo,etiquetaTicketPromedio,etiquetaPagosAcreditados,etiquetaOcupacion,etiquetaVariacionReservas,etiquetaVariacionIngresos;
    @FXML private Label hallazgoCancha,hallazgoHorario,hallazgoDia,hallazgoCliente,hallazgoMetodo;
    @FXML private Label reservaSolicitudes,reservaEfectivas,reservaPersonal,reservaWeb,reservaPendientes,reservaConfirmadas,reservaCompletadas,reservaCanceladas,reservaAusencias,reservaExpiradas,tasaConfirmacion,tasaFinalizacion,tasaCancelacion,tasaAusencia,tasaExpiracionWeb,tasaConversionWeb;
    @FXML private PieChart graficoReservasOrigen,graficoCancelacionesTipo;
    @FXML private Label finPagosRecibidos,finReembolsado,finIngresoFinal,finResultadoPeriodo,finCantidadPagos,finPagoPromedio,finIngresosCaja,finEgresosCaja,finPagosPendientes,finDiferenciaCaja;
    @FXML private PieChart graficoFinMetodos,graficoFinCajaTipo,graficoFinCajaMedio;
    @FXML private LineChart<String,Number> graficoFinPagosDia,graficoFinReembolsosDia,graficoFinResultadoDia,graficoFinDiferencias;
    @FXML private LineChart<String,Number> graficoEvolucionReservas,graficoEvolucionIncidencias;
    @FXML private PieChart graficoEstados,graficoMetodos; @FXML private BarChart<String,Number> graficoCanchas,graficoHorarios,graficoDias,graficoClientes; @FXML private LineChart<String,Number> graficoIngresos; @FXML private ScrollPane scrollEstadisticas;
    @FXML private TableView<CierreCaja> tablaCierres; @FXML private TableColumn<CierreCaja,LocalDate> columnaFechaCierre; @FXML private TableColumn<CierreCaja,BigDecimal> columnaTotalCierre,columnaEfectivoCalculado,columnaEfectivoDeclarado,columnaDiferencia,columnaReembolsado; @FXML private TableColumn<CierreCaja,String> columnaUsuario; @FXML private TableColumn<CierreCaja,LocalDateTime> columnaFechaHoraCierre;
    @FXML private VBox panelResumen,panelReservas,panelFinanzas,panelClientes,panelCanchas,panelWeb,panelProximamente;
    @FXML private Label cliTotal,cliActivos,cliNuevos,cliConReservas,cliRecurrentes,cliUnaReserva,cliPromedio,cliCuentaWeb,cliCuentasNuevas,cliTorneos,cliRecurrencia;
    @FXML private PieChart graficoCliEstado,graficoCliPosicion,graficoCliActividad;
    @FXML private LineChart<String,Number> graficoCliAltas;
    @FXML private VBox listaCliReservas,listaCliFacturacion;
    @FXML private Label canTotal,canActivas,canBloqueos,canCapacidad,canDisponible,canReservado,canBloqueado,canTorneos,canOcupacion,canUsoTotal,canPartidos,canReservasEfectivas,canPrincipalReservas,canPrincipalIngresos;
    @FXML private BarChart<String,Number> graficoCanUso,graficoCanIngresos,graficoCanBloqueos,graficoCanTorneos;
    @FXML private Label webSolicitudes,webConPago,webConfirmacion,webDinero,webPendientes,webExpiradas,webCanceladas,webCompletadas,webReembolsado,webTiempoPago,webTasaExpiracion;
    @FXML private PieChart graficoWebEstados,graficoWebMetodos;
    @FXML private BarChart<String,Number> graficoWebEmbudo,graficoWebHorarios,graficoWebDias;
    @FXML private LineChart<String,Number> graficoWebSolicitudes; @FXML private Label tituloProximamente,textoProximamente; @FXML private ToggleButton botonResumen,botonReservas,botonFinanzas,botonClientes,botonCanchas,botonWeb;

    @FXML private void initialize(){LocalDate h=LocalDate.now();fechaHasta.setValue(h);fechaDesde.setValue(h.withDayOfMonth(1));fechaDesde.setDayCellFactory(x->celda());fechaHasta.setDayCellFactory(x->celda());configurarGraficos();configurarTabla();mostrarResumen();Platform.runLater(this::actualizar);}
    private DateCell celda(){return new DateCell(){@Override public void updateItem(LocalDate f,boolean v){super.updateItem(f,v);setDisable(v||f==null||f.isAfter(LocalDate.now()));}};}
    private void configurarGraficos(){for(PieChart p:List.of(graficoEstados,graficoMetodos,graficoReservasOrigen,graficoCancelacionesTipo,graficoFinMetodos,graficoFinCajaTipo,graficoFinCajaMedio,graficoCliEstado,graficoCliPosicion,graficoCliActividad,graficoWebEstados,graficoWebMetodos)){p.setLegendVisible(true);p.setLegendSide(Side.BOTTOM);p.setLabelsVisible(false);p.setAnimated(false);}for(XYChart<String,Number> g:List.of(graficoCanchas,graficoHorarios,graficoDias,graficoClientes,graficoIngresos,graficoEvolucionReservas,graficoEvolucionIncidencias,graficoFinPagosDia,graficoFinReembolsosDia,graficoFinResultadoDia,graficoFinDiferencias,graficoCliAltas,graficoCanUso,graficoCanIngresos,graficoCanBloqueos,graficoCanTorneos,graficoWebEmbudo,graficoWebHorarios,graficoWebDias,graficoWebSolicitudes)){g.setAnimated(false);g.setLegendVisible(false);if(g.getYAxis() instanceof NumberAxis n){n.setForceZeroInRange(true);n.setMinorTickVisible(false);n.setAutoRanging(true);}}for(XYChart<String,Number> g:graficosConteo())configurarEjeEntero(g);}
    private List<XYChart<String,Number>> graficosConteo(){return List.of(graficoCanchas,graficoHorarios,graficoDias,graficoClientes,graficoEvolucionReservas,graficoEvolucionIncidencias,graficoCliAltas,graficoCanUso,graficoCanBloqueos,graficoCanTorneos,graficoWebEmbudo,graficoWebHorarios,graficoWebDias,graficoWebSolicitudes);}
    private void configurarEjeEntero(XYChart<String,Number> grafico){if(grafico.getYAxis() instanceof NumberAxis eje){eje.setMinorTickVisible(false);eje.setForceZeroInRange(true);eje.setTickUnit(1);}}
    private void configurarTabla(){columnaFechaCierre.setCellValueFactory(new PropertyValueFactory<>("fecha"));columnaTotalCierre.setCellValueFactory(new PropertyValueFactory<>("totalAcreditado"));columnaEfectivoCalculado.setCellValueFactory(new PropertyValueFactory<>("totalEfectivoCalculado"));columnaEfectivoDeclarado.setCellValueFactory(new PropertyValueFactory<>("efectivoDeclarado"));columnaDiferencia.setCellValueFactory(new PropertyValueFactory<>("diferenciaEfectivo"));columnaReembolsado.setCellValueFactory(new PropertyValueFactory<>("totalReembolsado"));columnaUsuario.setCellValueFactory(new PropertyValueFactory<>("nombreUsuarioCierre"));columnaFechaHoraCierre.setCellValueFactory(new PropertyValueFactory<>("fechaCierre"));columnaFechaCierre.setCellFactory(x->new TableCell<>(){@Override protected void updateItem(LocalDate v,boolean e){super.updateItem(v,e);setText(e||v==null?null:v.format(FECHA));}});columnaFechaHoraCierre.setCellFactory(x->new TableCell<>(){@Override protected void updateItem(LocalDateTime v,boolean e){super.updateItem(v,e);setText(e||v==null?null:v.format(FECHA_HORA));}});for(TableColumn<CierreCaja,BigDecimal> col:List.of(columnaTotalCierre,columnaEfectivoCalculado,columnaEfectivoDeclarado,columnaReembolsado)){col.setCellFactory(x->celdaMoneda());}columnaDiferencia.setCellFactory(x->new TableCell<>(){@Override protected void updateItem(BigDecimal v,boolean e){super.updateItem(v,e);getStyleClass().removeAll("stats-difference-positive","stats-difference-negative","stats-difference-zero");setAlignment(Pos.CENTER_RIGHT);setText(e||v==null?null:moneda(v));if(!e&&v!=null)getStyleClass().add(v.signum()>0?"stats-difference-positive":v.signum()<0?"stats-difference-negative":"stats-difference-zero");}});}
    private TableCell<CierreCaja,BigDecimal> celdaMoneda(){return new TableCell<>(){@Override protected void updateItem(BigDecimal v,boolean e){super.updateItem(v,e);setAlignment(Pos.CENTER_RIGHT);setText(e||v==null?null:moneda(v));}};}
    @FXML private void periodoHoy(){aplicarPeriodo(LocalDate.now(),LocalDate.now());} @FXML private void periodoMes(){LocalDate h=LocalDate.now();aplicarPeriodo(h.withDayOfMonth(1),h);} @FXML private void periodoTreinta(){LocalDate h=LocalDate.now();aplicarPeriodo(h.minusDays(29),h);} @FXML private void periodoAnio(){LocalDate h=LocalDate.now();aplicarPeriodo(h.withDayOfYear(1),h);} private void aplicarPeriodo(LocalDate d,LocalDate h){fechaDesde.setValue(d);fechaHasta.setValue(h);actualizar();}
    @FXML private void mostrarResumen(){mostrarSeccion(botonResumen,true,false,false,false,false,false,null,null);} @FXML private void mostrarReservas(){mostrarSeccion(botonReservas,false,true,false,false,false,false,null,null);} @FXML private void mostrarFinanzas(){mostrarSeccion(botonFinanzas,false,false,true,false,false,false,null,null);} @FXML private void mostrarClientes(){mostrarSeccion(botonClientes,false,false,false,true,false,false,null,null);} @FXML private void mostrarCanchas(){mostrarSeccion(botonCanchas,false,false,false,false,true,false,null,null);} @FXML private void mostrarWeb(){mostrarSeccion(botonWeb,false,false,false,false,false,true,null,null);}
    private void mostrarSeccion(ToggleButton activo,boolean resumen,boolean reservas,boolean finanzas,boolean clientes,boolean canchas,boolean web,String titulo,String texto){for(ToggleButton b:List.of(botonResumen,botonReservas,botonFinanzas,botonClientes,botonCanchas,botonWeb))b.setSelected(b==activo);panelResumen.setVisible(resumen);panelResumen.setManaged(resumen);panelReservas.setVisible(reservas);panelReservas.setManaged(reservas);panelFinanzas.setVisible(finanzas);panelFinanzas.setManaged(finanzas);panelClientes.setVisible(clientes);panelClientes.setManaged(clientes);panelCanchas.setVisible(canchas);panelCanchas.setManaged(canchas);panelWeb.setVisible(web);panelWeb.setManaged(web);boolean proximo=!resumen&&!reservas&&!finanzas&&!clientes&&!canchas&&!web;panelProximamente.setVisible(proximo);panelProximamente.setManaged(proximo);if(proximo){tituloProximamente.setText(titulo);textoProximamente.setText(texto);}reiniciarScroll();}
    private void reiniciarScroll(){if(scrollEstadisticas==null)return;Platform.runLater(()->{scrollEstadisticas.setHvalue(0);scrollEstadisticas.setVvalue(0);});}
    @FXML private void actualizar(){LocalDate d=fechaDesde.getValue(),h=fechaHasta.getValue();if(d==null||h==null){error("Seleccioná las dos fechas del período.");return;}if(h.isBefore(d)){error("La fecha final no puede ser anterior a la inicial.");return;}long dias=java.time.temporal.ChronoUnit.DAYS.between(d,h)+1;LocalDate ah=d.minusDays(1),ad=ah.minusDays(dias-1);etiquetaPeriodoComparado.setText("Período anterior: "+ad.format(FECHA)+" al "+ah.format(FECHA));carga(true,"Consultando estadísticas...");Task<EstadisticasPadel> t=new Task<>(){@Override protected EstadisticasPadel call(){return service.obtener(d,h);}};t.setOnSucceeded(e->{mostrar(t.getValue());carga(false,"Estadísticas actualizadas.");reiniciarScroll();});t.setOnFailed(e->{Throwable x=t.getException();if(x!=null)x.printStackTrace();error(x==null?"No se pudieron cargar las estadísticas.":x.getMessage());});Thread th=new Thread(t,"estadisticas-padel");th.setDaemon(true);th.start();}
    private void mostrar(EstadisticasPadel d){etiquetaTotalReservas.setText(String.valueOf(d.getTotalReservas()));etiquetaEfectivas.setText(String.valueOf(d.getReservasEfectivas()));etiquetaPendientes.setText(String.valueOf(d.getReservasPendientes()));etiquetaConfirmadas.setText(String.valueOf(d.getReservasConfirmadas()));etiquetaCompletadas.setText(String.valueOf(d.getReservasCompletadas()));etiquetaCanceladas.setText(d.getReservasCanceladas()+" · "+d.getTasaCancelacion()+" %");etiquetaAusencias.setText(d.getReservasAusentes()+" · "+d.getTasaAusencia()+" %");etiquetaExpiradas.setText(String.valueOf(d.getReservasExpiradas()));etiquetaIngresos.setText(moneda(d.getIngresosAcreditados()));etiquetaReembolsado.setText(moneda(d.getTotalReembolsado()));etiquetaIngresosNetos.setText(moneda(d.getIngresosNetos()));etiquetaIngresosManuales.setText(moneda(d.getIngresosManuales()));etiquetaEgresosManuales.setText(moneda(d.getEgresosManuales()));etiquetaResultadoOperativo.setText(moneda(d.getResultadoOperativo()));semanticaDinero(etiquetaResultadoOperativo,d.getResultadoOperativo());semanticaDinero(etiquetaEgresosManuales,d.getEgresosManuales().negate());semanticaDinero(etiquetaIngresosNetos,d.getIngresosNetos());etiquetaTicketPromedio.setText(moneda(d.getTicketPromedio()));etiquetaPagosAcreditados.setText(String.valueOf(d.getCantidadPagosAcreditados()));etiquetaOcupacion.setText(d.getPorcentajeOcupacion()+" %");variacion(etiquetaVariacionReservas,d.getVariacionReservas(),d.getTotalReservas());variacion(etiquetaVariacionIngresos,d.getVariacionIngresos(),d.getIngresosAcreditados().signum());pie(graficoEstados,d.getReservasPorEstado());pie(graficoMetodos,d.getIngresosPorMetodo());barras(graficoCanchas,d.getReservasPorCancha());barras(graficoHorarios,d.getHorariosMasSolicitados());barras(graficoDias,ordenarDias(d.getDiasMasSolicitados()));barras(graficoClientes,d.getClientesFrecuentes());linea(completarMeses(d.getIngresosPorMes()));tablaCierres.getItems().setAll(d.getCierresCaja());hallazgo(hallazgoCancha,d.getReservasPorCancha(),"Sin reservas");hallazgo(hallazgoHorario,d.getHorariosMasSolicitados(),"Sin horarios");hallazgo(hallazgoDia,d.getDiasMasSolicitados(),"Sin demanda");hallazgo(hallazgoCliente,d.getClientesFrecuentes(),"Sin clientes");hallazgo(hallazgoMetodo,d.getIngresosPorMetodo(),"Sin pagos");mostrarReservasPanel(d);mostrarFinanzasPanel(d);mostrarClientesPanel(d);mostrarCanchasPanel(d);mostrarWebPanel(d);}
    private void mostrarReservasPanel(EstadisticasPadel d){
        reservaSolicitudes.setText(String.valueOf(d.getTotalReservas()));reservaEfectivas.setText(String.valueOf(d.getReservasEfectivas()));reservaPersonal.setText(String.valueOf(d.getReservasPersonal()));reservaWeb.setText(String.valueOf(d.getReservasWeb()));reservaPendientes.setText(String.valueOf(d.getReservasPendientes()));reservaConfirmadas.setText(String.valueOf(d.getReservasConfirmadas()));reservaCompletadas.setText(String.valueOf(d.getReservasCompletadas()));reservaCanceladas.setText(String.valueOf(d.getReservasCanceladas()));reservaAusencias.setText(String.valueOf(d.getReservasAusentes()));reservaExpiradas.setText(String.valueOf(d.getReservasExpiradas()));tasaConfirmacion.setText(porcentaje(d.getTasaConfirmacion()));tasaFinalizacion.setText(porcentaje(d.getTasaFinalizacion()));tasaCancelacion.setText(porcentaje(d.getTasaCancelacion()));tasaAusencia.setText(porcentaje(d.getTasaAusencia()));tasaExpiracionWeb.setText(porcentaje(d.getTasaExpiracionWeb()));tasaConversionWeb.setText(porcentaje(d.getConversionWeb()));semanticaTasa(tasaConfirmacion,d.getTasaConfirmacion(),false);semanticaTasa(tasaFinalizacion,d.getTasaFinalizacion(),false);semanticaTasa(tasaCancelacion,d.getTasaCancelacion(),true);semanticaTasa(tasaAusencia,d.getTasaAusencia(),true);semanticaTasa(tasaExpiracionWeb,d.getTasaExpiracionWeb(),true);semanticaTasa(tasaConversionWeb,d.getConversionWeb(),false);
        cargarPieOrigen(d);pie(graficoCancelacionesTipo,d.getCancelacionesPorTipo());lineaEn(graficoEvolucionReservas,completarDias(d.getReservasPorDia()));cargarIncidencias(d);
    }
    private String porcentaje(BigDecimal v){return v.setScale(2,RoundingMode.HALF_UP).toPlainString()+" %";}
    private void cargarPieOrigen(EstadisticasPadel d){pie(graficoReservasOrigen,List.of(new DatoGrafico("Personal",BigDecimal.valueOf(d.getReservasPersonal())),new DatoGrafico("Web",BigDecimal.valueOf(d.getReservasWeb()))));}
    private List<DatoGrafico> completarDias(List<DatoGrafico> datos){Map<String,BigDecimal> mapa=new HashMap<>();for(DatoGrafico x:datos)mapa.put(x.etiqueta(),x.valor());java.util.ArrayList<DatoGrafico> salida=new java.util.ArrayList<>();LocalDate dia=fechaDesde.getValue();while(!dia.isAfter(fechaHasta.getValue())){String clave=dia.toString();salida.add(new DatoGrafico(dia.format(DateTimeFormatter.ofPattern("dd/MM")),mapa.getOrDefault(clave,BigDecimal.ZERO)));dia=dia.plusDays(1);}return salida;}
    private void cargarIncidencias(EstadisticasPadel d){Map<String,BigDecimal> porDia=new java.util.LinkedHashMap<>();for(DatoGrafico x:d.getEvolucionIncidencias()){String dia=x.etiqueta().split("\\|")[0];porDia.merge(dia,x.valor(),BigDecimal::add);}java.util.ArrayList<DatoGrafico> datos=new java.util.ArrayList<>();for(Map.Entry<String,BigDecimal> e:porDia.entrySet()){LocalDate fecha=LocalDate.parse(e.getKey());datos.add(new DatoGrafico(fecha.format(DateTimeFormatter.ofPattern("dd/MM")),e.getValue()));}lineaEn(graficoEvolucionIncidencias,datos);}
    private void lineaEn(LineChart<String,Number> grafico,List<DatoGrafico> datos){grafico.getData().clear();if(sinActividad(datos)){mostrarSinDatos(grafico,"Sin actividad en el período");ajustarEje(grafico,datos);return;}restaurarGrafico(grafico);XYChart.Series<String,Number> serie=new XYChart.Series<>();for(DatoGrafico x:datos)serie.getData().add(new XYChart.Data<>(x.etiqueta(),x.valor()));grafico.getData().add(serie);ajustarEje(grafico,datos);}

    private void mostrarFinanzasPanel(EstadisticasPadel d){
        finPagosRecibidos.setText(moneda(d.getIngresosAcreditados()));finReembolsado.setText(moneda(d.getTotalReembolsado()));finIngresoFinal.setText(moneda(d.getIngresosNetos()));finResultadoPeriodo.setText(moneda(d.getResultadoOperativo()));finCantidadPagos.setText(String.valueOf(d.getCantidadPagosAcreditados()));finPagoPromedio.setText(moneda(d.getTicketPromedio()));finIngresosCaja.setText(moneda(d.getIngresosManuales()));finEgresosCaja.setText(moneda(d.getEgresosManuales()));finPagosPendientes.setText(String.valueOf(d.getPagosPendientes()));finDiferenciaCaja.setText(moneda(d.getDiferenciaEfectivoAcumulada()));semanticaDinero(finPagosRecibidos,d.getIngresosAcreditados());semanticaDinero(finReembolsado,d.getTotalReembolsado().negate());semanticaDinero(finIngresoFinal,d.getIngresosNetos());semanticaDinero(finResultadoPeriodo,d.getResultadoOperativo());semanticaDinero(finIngresosCaja,d.getIngresosManuales());semanticaDinero(finEgresosCaja,d.getEgresosManuales().negate());semanticaDiferencia(finDiferenciaCaja,d.getDiferenciaEfectivoAcumulada());
        pie(graficoFinMetodos,d.getIngresosPorMetodo());pie(graficoFinCajaTipo,d.getMovimientosCajaPorTipo());pieConValoresAbsolutos(graficoFinCajaMedio,d.getMovimientosCajaPorMedio());
        lineaEn(graficoFinPagosDia,completarSerieDiaria(d.getPagosRecibidosPorDia()));lineaEn(graficoFinReembolsosDia,completarSerieDiaria(d.getReembolsosPorDia()));lineaEn(graficoFinResultadoDia,resultadoDiario(d));lineaEn(graficoFinDiferencias,formatearSerieFechas(d.getDiferenciasCajaPorDia()));
    }
    private void pieConValoresAbsolutos(PieChart grafico,List<DatoGrafico> datos){java.util.ArrayList<DatoGrafico> absolutos=new java.util.ArrayList<>();for(DatoGrafico x:datos)absolutos.add(new DatoGrafico(x.etiqueta(),x.valor().abs()));pie(grafico,absolutos);}
    private List<DatoGrafico> completarSerieDiaria(List<DatoGrafico> datos){Map<String,BigDecimal> mapa=new HashMap<>();for(DatoGrafico x:datos)mapa.put(x.etiqueta(),x.valor());java.util.ArrayList<DatoGrafico> salida=new java.util.ArrayList<>();LocalDate dia=fechaDesde.getValue();while(!dia.isAfter(fechaHasta.getValue())){salida.add(new DatoGrafico(dia.format(DateTimeFormatter.ofPattern("dd/MM")),mapa.getOrDefault(dia.toString(),BigDecimal.ZERO)));dia=dia.plusDays(1);}return salida;}
    private List<DatoGrafico> formatearSerieFechas(List<DatoGrafico> datos){java.util.ArrayList<DatoGrafico> salida=new java.util.ArrayList<>();for(DatoGrafico x:datos){salida.add(new DatoGrafico(LocalDate.parse(x.etiqueta()).format(DateTimeFormatter.ofPattern("dd/MM")),x.valor()));}return salida;}
    private List<DatoGrafico> resultadoDiario(EstadisticasPadel d){Map<String,BigDecimal> pagos=new HashMap<>(),reembolsos=new HashMap<>();for(DatoGrafico x:d.getPagosRecibidosPorDia())pagos.put(x.etiqueta(),x.valor());for(DatoGrafico x:d.getReembolsosPorDia())reembolsos.put(x.etiqueta(),x.valor());java.util.ArrayList<DatoGrafico> salida=new java.util.ArrayList<>();LocalDate dia=fechaDesde.getValue();while(!dia.isAfter(fechaHasta.getValue())){String clave=dia.toString();BigDecimal valor=pagos.getOrDefault(clave,BigDecimal.ZERO).subtract(reembolsos.getOrDefault(clave,BigDecimal.ZERO));salida.add(new DatoGrafico(dia.format(DateTimeFormatter.ofPattern("dd/MM")),valor));dia=dia.plusDays(1);}return salida;}

    private void mostrarClientesPanel(EstadisticasPadel d){cliTotal.setText(String.valueOf(d.getTotalClientes()));cliActivos.setText(String.valueOf(d.getClientesActivos()));cliNuevos.setText(String.valueOf(d.getClientesNuevos()));cliConReservas.setText(String.valueOf(d.getClientesConReservas()));cliRecurrentes.setText(String.valueOf(d.getClientesRecurrentes()));cliUnaReserva.setText(String.valueOf(d.getClientesUnaReserva()));cliPromedio.setText(d.getPromedioReservasPorCliente().setScale(2,RoundingMode.HALF_UP).toPlainString());cliCuentaWeb.setText(String.valueOf(d.getClientesConCuentaWeb()));cliCuentasNuevas.setText(String.valueOf(d.getCuentasWebNuevas()));cliTorneos.setText(String.valueOf(d.getParticipantesTorneos()));cliRecurrencia.setText(porcentaje(d.getPorcentajeClientesRecurrentes()));semanticaTasa(cliRecurrencia,d.getPorcentajeClientesRecurrentes(),false);pie(graficoCliEstado,List.of(new DatoGrafico("Activos",BigDecimal.valueOf(d.getClientesActivos())),new DatoGrafico("Inactivos",BigDecimal.valueOf(d.getClientesInactivos()))));pie(graficoCliPosicion,d.getClientesPorPosicion());pie(graficoCliActividad,d.getActividadClientes());lineaEn(graficoCliAltas,completarMeses(d.getClientesNuevosPorMes()));ranking(listaCliReservas,d.getClientesFrecuentes(),false);ranking(listaCliFacturacion,d.getClientesPorFacturacion(),true);}
    private void ranking(VBox contenedor,List<DatoGrafico> datos,boolean dinero){contenedor.getChildren().clear();if(datos.isEmpty()){Label vacio=new Label("No hay datos para el período seleccionado.");vacio.getStyleClass().add("stats-ranking-empty");contenedor.getChildren().add(vacio);return;}int posicion=1;for(DatoGrafico dato:datos){javafx.scene.layout.HBox fila=new javafx.scene.layout.HBox(10);fila.setAlignment(Pos.CENTER_LEFT);fila.getStyleClass().add("stats-ranking-row");Label numero=new Label(String.valueOf(posicion++));numero.getStyleClass().add("stats-ranking-number");Label nombre=new Label(dato.etiqueta());nombre.getStyleClass().add("stats-ranking-name");javafx.scene.layout.HBox.setHgrow(nombre,javafx.scene.layout.Priority.ALWAYS);Label valor=new Label(dinero?moneda(dato.valor()):dato.valor().stripTrailingZeros().toPlainString()+" reservas");valor.getStyleClass().add("stats-ranking-value");fila.getChildren().addAll(numero,nombre,valor);contenedor.getChildren().add(fila);}}

    private void mostrarCanchasPanel(EstadisticasPadel d){canTotal.setText(String.valueOf(d.getTotalCanchas()));canActivas.setText(String.valueOf(d.getCanchasActivas()));canReservasEfectivas.setText(String.valueOf(d.getReservasEfectivas()));canPrincipalReservas.setText(principal(d.getReservasPorCancha(),"Sin reservas"));canPrincipalIngresos.setText(principalMoneda(d.getIngresosPorCancha(),"Sin pagos"));canCapacidad.setText(minutos(d.getMinutosCapacidad()));canDisponible.setText(minutos(d.getCapacidadDisponible()));canReservado.setText(minutos(d.getMinutosReservados()));canBloqueado.setText(minutos(d.getMinutosBloqueados()));canTorneos.setText(minutos(d.getMinutosTorneos()));canOcupacion.setText(porcentaje(d.getOcupacionReservasReal()));canUsoTotal.setText(porcentaje(d.getUsoTotalCanchas()));semanticaOcupacion(canOcupacion,d.getOcupacionReservasReal());semanticaOcupacion(canUsoTotal,d.getUsoTotalCanchas());canPartidos.setText(String.valueOf(d.getPartidosTorneo()));canBloqueos.setText(d.getBloqueosPorCancha().stream().map(DatoGrafico::valor).reduce(BigDecimal.ZERO,BigDecimal::add).stripTrailingZeros().toPlainString());barras(graficoCanUso,d.getReservasPorCancha());barras(graficoCanIngresos,d.getIngresosPorCancha());barras(graficoCanBloqueos,d.getBloqueosPorCancha());barras(graficoCanTorneos,d.getTorneosPorCancha());}
    private String principal(List<DatoGrafico> datos,String vacio){return datos.isEmpty()?vacio:datos.get(0).etiqueta()+" · "+datos.get(0).valor().stripTrailingZeros().toPlainString();}
    private String principalMoneda(List<DatoGrafico> datos,String vacio){return datos.isEmpty()?vacio:datos.get(0).etiqueta()+" · "+moneda(datos.get(0).valor());}
    private String minutos(BigDecimal v){long m=v==null?0:v.longValue();return (m/60)+" h "+(m%60)+" min";}

    private void mostrarWebPanel(EstadisticasPadel d){webSolicitudes.setText(String.valueOf(d.getWebSolicitudesCreadas()));webConPago.setText(String.valueOf(d.getWebConPago()));webConfirmacion.setText(porcentaje(d.getWebTasaAcreditacion()));webDinero.setText(moneda(d.getWebDineroRecibido()));webPendientes.setText(String.valueOf(d.getWebPendientes()));webExpiradas.setText(String.valueOf(d.getWebExpiradas()));webCanceladas.setText(String.valueOf(d.getWebCanceladas()));webCompletadas.setText(String.valueOf(d.getWebCompletadas()));webReembolsado.setText(moneda(d.getWebDineroReembolsado()));webTiempoPago.setText(duracionMinutos(d.getWebPromedioMinutosPrimerPago()));webTasaExpiracion.setText(porcentaje(d.getWebTasaExpiracion()));semanticaTasa(webConfirmacion,d.getWebTasaAcreditacion(),false);semanticaDinero(webDinero,d.getWebDineroRecibido());semanticaDinero(webReembolsado,d.getWebDineroReembolsado().negate());semanticaTasa(webTasaExpiracion,d.getWebTasaExpiracion(),true);pie(graficoWebEstados,d.getWebEstados());pie(graficoWebMetodos,d.getWebMetodosPago());barras(graficoWebEmbudo,d.getWebEmbudo());barras(graficoWebHorarios,d.getWebHorarios());barras(graficoWebDias,ordenarDias(d.getWebDias()));lineaEn(graficoWebSolicitudes,completarSerieDiaria(d.getWebSolicitudesPorDia()));}
    private String duracionMinutos(BigDecimal valor){long minutos=valor==null?0:valor.setScale(0,RoundingMode.HALF_UP).longValue();if(minutos<60)return minutos+" min";return (minutos/60)+" h "+(minutos%60)+" min";}

    private void claseSemantica(Label etiqueta,String clase){etiqueta.getStyleClass().removeAll("stats-value-positive-v4","stats-value-warning-v4","stats-value-negative-v4","stats-value-neutral-v4");etiqueta.getStyleClass().add(clase);}
    private void semanticaDinero(Label etiqueta,BigDecimal valor){BigDecimal v=valor==null?BigDecimal.ZERO:valor;claseSemantica(etiqueta,v.signum()>0?"stats-value-positive-v4":v.signum()<0?"stats-value-negative-v4":"stats-value-neutral-v4");}
    private void semanticaDiferencia(Label etiqueta,BigDecimal valor){BigDecimal v=valor==null?BigDecimal.ZERO:valor;claseSemantica(etiqueta,v.signum()==0?"stats-value-positive-v4":"stats-value-warning-v4");}
    private void semanticaTasa(Label etiqueta,BigDecimal valor,boolean inversa){BigDecimal v=valor==null?BigDecimal.ZERO:valor;if(inversa){claseSemantica(etiqueta,v.signum()==0?"stats-value-positive-v4":v.compareTo(BigDecimal.valueOf(10))<0?"stats-value-warning-v4":"stats-value-negative-v4");}else{claseSemantica(etiqueta,v.signum()==0?"stats-value-neutral-v4":v.compareTo(BigDecimal.valueOf(50))>=0?"stats-value-positive-v4":"stats-value-warning-v4");}}
    private void semanticaOcupacion(Label etiqueta,BigDecimal valor){BigDecimal v=valor==null?BigDecimal.ZERO:valor;claseSemantica(etiqueta,v.compareTo(BigDecimal.valueOf(20))<0?"stats-value-warning-v4":v.compareTo(BigDecimal.valueOf(85))>0?"stats-value-negative-v4":"stats-value-positive-v4");}
    private void variacion(Label l,BigDecimal v,int actual){if(actual>0&&v.compareTo(BigDecimal.valueOf(100))==0){l.setText("Sin base de comparación");l.getStyleClass().setAll("label","stats-trend-flat");return;}l.setText((v.signum()>0?"+":"")+v+" % frente al período anterior");l.getStyleClass().removeAll("stats-trend-up","stats-trend-down","stats-trend-flat");l.getStyleClass().add(v.signum()>0?"stats-trend-up":v.signum()<0?"stats-trend-down":"stats-trend-flat");}
    private void hallazgo(Label l,List<DatoGrafico> ds,String vacio){l.setText(ds.isEmpty()?vacio:etiqueta(ds.get(0).etiqueta())+" · "+ds.get(0).valor().stripTrailingZeros().toPlainString());}
    private List<DatoGrafico> ordenarDias(List<DatoGrafico> ds){Map<String,BigDecimal> m=new HashMap<>();for(DatoGrafico d:ds)m.put(d.etiqueta().toLowerCase(Locale.ROOT),d.valor());return List.of("Lunes","Martes","Miércoles","Jueves","Viernes","Sábado","Domingo").stream().map(x->new DatoGrafico(x,m.getOrDefault(x.toLowerCase(Locale.ROOT),BigDecimal.ZERO))).toList();}
    private List<DatoGrafico> completarMeses(List<DatoGrafico> ds){LocalDate d=fechaDesde.getValue().withDayOfMonth(1),h=fechaHasta.getValue().withDayOfMonth(1);Map<String,BigDecimal> m=new HashMap<>();for(DatoGrafico x:ds)m.put(x.etiqueta(),x.valor());java.util.ArrayList<DatoGrafico> out=new java.util.ArrayList<>();while(!d.isAfter(h)){String key=d.format(DateTimeFormatter.ofPattern("yyyy-MM"));String label=d.getMonth().getDisplayName(TextStyle.SHORT,new Locale("es","AR"))+" "+d.getYear();out.add(new DatoGrafico(label,m.getOrDefault(key,BigDecimal.ZERO)));d=d.plusMonths(1);}return out;}
    private void pie(PieChart g,List<DatoGrafico> ds){g.getData().clear();List<DatoGrafico> positivos=ds==null?List.of():ds.stream().filter(x->x.valor()!=null&&x.valor().signum()>0).toList();if(positivos.isEmpty()){mostrarSinDatos(g,"Sin datos para el período");g.setLegendVisible(false);return;}restaurarGrafico(g);g.setLegendVisible(true);for(DatoGrafico d:positivos)g.getData().add(new PieChart.Data(etiqueta(d.etiqueta()),d.valor().doubleValue()));if(positivos.size()==1)g.setTitle(etiqueta(positivos.get(0).etiqueta())+" · 100 %");}
    private void barras(BarChart<String,Number> g,List<DatoGrafico> ds){g.getData().clear();if(sinActividad(ds)){mostrarSinDatos(g,"Sin actividad en el período");ajustarEje(g,ds);return;}restaurarGrafico(g);XYChart.Series<String,Number>s=new XYChart.Series<>();for(DatoGrafico d:ds)s.getData().add(new XYChart.Data<>(etiqueta(d.etiqueta()),d.valor()));g.getData().add(s);ajustarEje(g,ds);}
    private void linea(List<DatoGrafico> ds){lineaEn(graficoIngresos,ds);}
    private boolean sinActividad(List<DatoGrafico> datos){return datos==null||datos.isEmpty()||datos.stream().allMatch(x->x.valor()==null||x.valor().signum()==0);}
    private void mostrarSinDatos(Chart grafico,String mensaje){grafico.setTitle(mensaje);grafico.getStyleClass().remove("stats-chart-has-data-v3");if(!grafico.getStyleClass().contains("stats-chart-empty-v3"))grafico.getStyleClass().add("stats-chart-empty-v3");}
    private void restaurarGrafico(Chart grafico){grafico.setTitle(null);grafico.getStyleClass().remove("stats-chart-empty-v3");if(!grafico.getStyleClass().contains("stats-chart-has-data-v3"))grafico.getStyleClass().add("stats-chart-has-data-v3");}
    private void ajustarEje(XYChart<String,Number> grafico,List<DatoGrafico> datos){if(!(grafico.getYAxis() instanceof NumberAxis eje))return;BigDecimal max=BigDecimal.ZERO;BigDecimal min=BigDecimal.ZERO;if(datos!=null)for(DatoGrafico dato:datos){BigDecimal valor=dato.valor()==null?BigDecimal.ZERO:dato.valor();if(valor.compareTo(max)>0)max=valor;if(valor.compareTo(min)<0)min=valor;}boolean conteo=graficosConteo().contains(grafico);eje.setAutoRanging(false);double superior=max.signum()==0?1:max.doubleValue()*1.15;double inferior=min.signum()<0?min.doubleValue()*1.15:0;if(conteo){superior=Math.max(1,Math.ceil(superior));eje.setTickUnit(Math.max(1,Math.ceil(superior/6)));}else{double rango=Math.max(1,superior-inferior);eje.setTickUnit(redondearUnidad(rango/6));}eje.setLowerBound(inferior);eje.setUpperBound(superior);}
    private double redondearUnidad(double valor){if(valor<=1)return 1;double magnitud=Math.pow(10,Math.floor(Math.log10(valor)));return Math.ceil(valor/magnitud)*magnitud;}
    private String etiqueta(String v){if(v==null||v.isBlank())return "Sin datos";String t=v.replace('_',' ').toLowerCase(Locale.ROOT);return Character.toUpperCase(t.charAt(0))+t.substring(1);}
    private String moneda(BigDecimal v){return NumberFormat.getCurrencyInstance(new Locale("es","AR")).format(v==null?BigDecimal.ZERO:v.setScale(2,RoundingMode.HALF_UP));}
    private void carga(boolean c,String m){indicadorCarga.setVisible(c);botonActualizar.setDisable(c);etiquetaEstado.setText(m);etiquetaEstado.getStyleClass().removeAll("stats-status-ok","stats-status-error");if(!c)etiquetaEstado.getStyleClass().add("stats-status-ok");}
    private void error(String m){indicadorCarga.setVisible(false);botonActualizar.setDisable(false);etiquetaEstado.setText(m==null?"No se pudieron cargar las estadísticas.":m);etiquetaEstado.getStyleClass().removeAll("stats-status-ok","stats-status-error");etiquetaEstado.getStyleClass().add("stats-status-error");}
    @FXML private void descargarGuiaPdf(){
        var configuracion=configuracionService.obtener();
        FileChooser selector=new FileChooser();
        selector.setTitle("Guardar guía de estadísticas");
        selector.getExtensionFilters().add(new FileChooser.ExtensionFilter("Documento PDF","*.pdf"));
        selector.setInitialFileName(nombreGuiaPdf(configuracion.getNombreComercial()));
        File destino=selector.showSaveDialog(scrollEstadisticas.getScene().getWindow());
        if(destino==null)return;
        if(!destino.getName().toLowerCase(Locale.ROOT).endsWith(".pdf"))destino=new File(destino.getParentFile(),destino.getName()+".pdf");
        try{
            File archivo=destino;
            guiaPdfService.generar(archivo,configuracion);
            Dialogos.exito("Guía de estadísticas generada","El PDF se guardó correctamente.");
            if(Desktop.isDesktopSupported()&&Desktop.getDesktop().isSupported(Desktop.Action.OPEN))Desktop.getDesktop().open(archivo);
        }catch(Exception exception){Dialogos.error("No se pudo generar la guía",exception.getMessage()==null?"No se pudo crear o abrir el archivo PDF.":exception.getMessage());}
    }
    private String nombreGuiaPdf(String nombre){String base=nombre==null||nombre.isBlank()?"padel-reservas":nombre.toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9]+","-").replaceAll("(^-|-$)","");return "guia-estadisticas-"+base+".pdf";}

    @FXML private void mostrarAyuda(){
        String seccion=botonReservas.isSelected()?"RESERVAS":botonFinanzas.isSelected()?"FINANZAS":botonClientes.isSelected()?"CLIENTES":botonCanchas.isSelected()?"CANCHAS":botonWeb.isSelected()?"WEB":"RESUMEN";
        AyudaEstadisticasDialogo.mostrar(seccion);
    }
    @FXML private void volver(){Navegacion.mostrarDashboard(Navegacion.getUsuarioActual());}
}
