package vista.controlador;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.text.NumberFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.TextStyle;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

import javafx.application.Platform;
import javafx.concurrent.Task;
import javafx.fxml.FXML;
import javafx.geometry.Pos;
import javafx.geometry.Side;
import javafx.scene.chart.BarChart;
import javafx.scene.chart.LineChart;
import javafx.scene.chart.NumberAxis;
import javafx.scene.chart.PieChart;
import javafx.scene.chart.XYChart;
import javafx.scene.control.Button;
import javafx.scene.control.DateCell;
import javafx.scene.control.DatePicker;
import javafx.scene.control.Label;
import javafx.scene.control.ProgressIndicator;
import javafx.scene.control.ScrollPane;
import javafx.scene.control.TableCell;
import javafx.scene.control.TableColumn;
import javafx.scene.control.TableView;
import javafx.scene.control.ToggleButton;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.scene.layout.VBox;
import negocio.CierreCaja;
import negocio.EstadisticasPadel;
import negocio.EstadisticasPadel.DatoGrafico;
import servicio.EstadisticasService;
import vista.Navegacion;

public class EstadisticasController {
    private static final DateTimeFormatter FECHA=DateTimeFormatter.ofPattern("dd/MM/yyyy"), FECHA_HORA=DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
    private final EstadisticasService service=new EstadisticasService();
    @FXML private DatePicker fechaDesde,fechaHasta; @FXML private Button botonActualizar; @FXML private ProgressIndicator indicadorCarga; @FXML private Label etiquetaEstado,etiquetaPeriodoComparado;
    @FXML private Label etiquetaTotalReservas,etiquetaEfectivas,etiquetaPendientes,etiquetaConfirmadas,etiquetaCompletadas,etiquetaCanceladas,etiquetaAusencias,etiquetaExpiradas,etiquetaIngresos,etiquetaReembolsado,etiquetaIngresosNetos,etiquetaIngresosManuales,etiquetaEgresosManuales,etiquetaResultadoOperativo,etiquetaTicketPromedio,etiquetaPagosAcreditados,etiquetaOcupacion,etiquetaVariacionReservas,etiquetaVariacionIngresos;
    @FXML private Label hallazgoCancha,hallazgoHorario,hallazgoDia,hallazgoCliente,hallazgoMetodo;
    @FXML private Label reservaSolicitudes,reservaEfectivas,reservaPersonal,reservaWeb,reservaPendientes,reservaConfirmadas,reservaCompletadas,reservaCanceladas,reservaAusencias,reservaExpiradas,tasaConfirmacion,tasaFinalizacion,tasaCancelacion,tasaAusencia,tasaExpiracionWeb,tasaConversionWeb;
    @FXML private PieChart graficoReservasOrigen,graficoCancelacionesTipo;
    @FXML private LineChart<String,Number> graficoEvolucionReservas,graficoEvolucionIncidencias;
    @FXML private PieChart graficoEstados,graficoMetodos; @FXML private BarChart<String,Number> graficoCanchas,graficoHorarios,graficoDias,graficoClientes; @FXML private LineChart<String,Number> graficoIngresos; @FXML private ScrollPane scrollEstadisticas;
    @FXML private TableView<CierreCaja> tablaCierres; @FXML private TableColumn<CierreCaja,LocalDate> columnaFechaCierre; @FXML private TableColumn<CierreCaja,BigDecimal> columnaTotalCierre,columnaEfectivoCalculado,columnaEfectivoDeclarado,columnaDiferencia,columnaReembolsado; @FXML private TableColumn<CierreCaja,String> columnaUsuario; @FXML private TableColumn<CierreCaja,LocalDateTime> columnaFechaHoraCierre;
    @FXML private VBox panelResumen,panelReservas,panelProximamente; @FXML private Label tituloProximamente,textoProximamente; @FXML private ToggleButton botonResumen,botonReservas,botonFinanzas,botonClientes,botonCanchas,botonWeb;

    @FXML private void initialize(){LocalDate h=LocalDate.now();fechaHasta.setValue(h);fechaDesde.setValue(h.withDayOfMonth(1));fechaDesde.setDayCellFactory(x->celda());fechaHasta.setDayCellFactory(x->celda());configurarGraficos();configurarTabla();mostrarResumen();Platform.runLater(this::actualizar);}
    private DateCell celda(){return new DateCell(){@Override public void updateItem(LocalDate f,boolean v){super.updateItem(f,v);setDisable(v||f==null||f.isAfter(LocalDate.now()));}};}
    private void configurarGraficos(){for(PieChart p:List.of(graficoEstados,graficoMetodos,graficoReservasOrigen,graficoCancelacionesTipo)){p.setLegendVisible(true);p.setLegendSide(Side.BOTTOM);p.setLabelsVisible(false);p.setAnimated(false);}for(XYChart<String,Number> g:List.of(graficoCanchas,graficoHorarios,graficoDias,graficoClientes,graficoIngresos,graficoEvolucionReservas,graficoEvolucionIncidencias)){g.setAnimated(false);g.setLegendVisible(false);if(g.getYAxis() instanceof NumberAxis n){n.setForceZeroInRange(true);n.setMinorTickVisible(false);}}}
    private void configurarTabla(){columnaFechaCierre.setCellValueFactory(new PropertyValueFactory<>("fecha"));columnaTotalCierre.setCellValueFactory(new PropertyValueFactory<>("totalAcreditado"));columnaEfectivoCalculado.setCellValueFactory(new PropertyValueFactory<>("totalEfectivoCalculado"));columnaEfectivoDeclarado.setCellValueFactory(new PropertyValueFactory<>("efectivoDeclarado"));columnaDiferencia.setCellValueFactory(new PropertyValueFactory<>("diferenciaEfectivo"));columnaReembolsado.setCellValueFactory(new PropertyValueFactory<>("totalReembolsado"));columnaUsuario.setCellValueFactory(new PropertyValueFactory<>("nombreUsuarioCierre"));columnaFechaHoraCierre.setCellValueFactory(new PropertyValueFactory<>("fechaCierre"));columnaFechaCierre.setCellFactory(x->new TableCell<>(){@Override protected void updateItem(LocalDate v,boolean e){super.updateItem(v,e);setText(e||v==null?null:v.format(FECHA));}});columnaFechaHoraCierre.setCellFactory(x->new TableCell<>(){@Override protected void updateItem(LocalDateTime v,boolean e){super.updateItem(v,e);setText(e||v==null?null:v.format(FECHA_HORA));}});for(TableColumn<CierreCaja,BigDecimal> col:List.of(columnaTotalCierre,columnaEfectivoCalculado,columnaEfectivoDeclarado,columnaReembolsado)){col.setCellFactory(x->celdaMoneda());}columnaDiferencia.setCellFactory(x->new TableCell<>(){@Override protected void updateItem(BigDecimal v,boolean e){super.updateItem(v,e);getStyleClass().removeAll("stats-difference-positive","stats-difference-negative","stats-difference-zero");setAlignment(Pos.CENTER_RIGHT);setText(e||v==null?null:moneda(v));if(!e&&v!=null)getStyleClass().add(v.signum()>0?"stats-difference-positive":v.signum()<0?"stats-difference-negative":"stats-difference-zero");}});}
    private TableCell<CierreCaja,BigDecimal> celdaMoneda(){return new TableCell<>(){@Override protected void updateItem(BigDecimal v,boolean e){super.updateItem(v,e);setAlignment(Pos.CENTER_RIGHT);setText(e||v==null?null:moneda(v));}};}
    @FXML private void periodoHoy(){aplicarPeriodo(LocalDate.now(),LocalDate.now());} @FXML private void periodoMes(){LocalDate h=LocalDate.now();aplicarPeriodo(h.withDayOfMonth(1),h);} @FXML private void periodoTreinta(){LocalDate h=LocalDate.now();aplicarPeriodo(h.minusDays(29),h);} @FXML private void periodoAnio(){LocalDate h=LocalDate.now();aplicarPeriodo(h.withDayOfYear(1),h);} private void aplicarPeriodo(LocalDate d,LocalDate h){fechaDesde.setValue(d);fechaHasta.setValue(h);actualizar();}
    @FXML private void mostrarResumen(){mostrarSeccion(botonResumen,true,false,null,null);} @FXML private void mostrarReservas(){mostrarSeccion(botonReservas,false,true,null,null);} @FXML private void mostrarFinanzas(){mostrarSeccion(botonFinanzas,false,false,"Estadísticas financieras","La próxima etapa incorporará pagos, reembolsos, caja manual y evolución neta.");} @FXML private void mostrarClientes(){mostrarSeccion(botonClientes,false,false,"Estadísticas de clientes","Se incorporarán altas, recurrencia, frecuencia y facturación por cliente.");} @FXML private void mostrarCanchas(){mostrarSeccion(botonCanchas,false,false,"Estadísticas de canchas","Se incorporarán ocupación, ingresos, bloqueos y uso por cancha.");} @FXML private void mostrarWeb(){mostrarSeccion(botonWeb,false,false,"Estadísticas web","Se incorporarán solicitudes, conversión, expiraciones y tiempos de acreditación.");}
    private void mostrarSeccion(ToggleButton activo,boolean resumen,boolean reservas,String titulo,String texto){for(ToggleButton b:List.of(botonResumen,botonReservas,botonFinanzas,botonClientes,botonCanchas,botonWeb))b.setSelected(b==activo);panelResumen.setVisible(resumen);panelResumen.setManaged(resumen);panelReservas.setVisible(reservas);panelReservas.setManaged(reservas);boolean proximo=!resumen&&!reservas;panelProximamente.setVisible(proximo);panelProximamente.setManaged(proximo);if(proximo){tituloProximamente.setText(titulo);textoProximamente.setText(texto);}if(scrollEstadisticas!=null)scrollEstadisticas.setVvalue(0);}
    @FXML private void actualizar(){LocalDate d=fechaDesde.getValue(),h=fechaHasta.getValue();if(d==null||h==null){error("Seleccioná las dos fechas del período.");return;}if(h.isBefore(d)){error("La fecha final no puede ser anterior a la inicial.");return;}long dias=java.time.temporal.ChronoUnit.DAYS.between(d,h)+1;LocalDate ah=d.minusDays(1),ad=ah.minusDays(dias-1);etiquetaPeriodoComparado.setText("Período anterior: "+ad.format(FECHA)+" al "+ah.format(FECHA));carga(true,"Consultando estadísticas...");Task<EstadisticasPadel> t=new Task<>(){@Override protected EstadisticasPadel call(){return service.obtener(d,h);}};t.setOnSucceeded(e->{mostrar(t.getValue());carga(false,"Estadísticas actualizadas.");Platform.runLater(()->scrollEstadisticas.setVvalue(0));});t.setOnFailed(e->{Throwable x=t.getException();if(x!=null)x.printStackTrace();error(x==null?"No se pudieron cargar las estadísticas.":x.getMessage());});Thread th=new Thread(t,"estadisticas-padel");th.setDaemon(true);th.start();}
    private void mostrar(EstadisticasPadel d){etiquetaTotalReservas.setText(String.valueOf(d.getTotalReservas()));etiquetaEfectivas.setText(String.valueOf(d.getReservasEfectivas()));etiquetaPendientes.setText(String.valueOf(d.getReservasPendientes()));etiquetaConfirmadas.setText(String.valueOf(d.getReservasConfirmadas()));etiquetaCompletadas.setText(String.valueOf(d.getReservasCompletadas()));etiquetaCanceladas.setText(d.getReservasCanceladas()+" · "+d.getTasaCancelacion()+" %");etiquetaAusencias.setText(d.getReservasAusentes()+" · "+d.getTasaAusencia()+" %");etiquetaExpiradas.setText(String.valueOf(d.getReservasExpiradas()));etiquetaIngresos.setText(moneda(d.getIngresosAcreditados()));etiquetaReembolsado.setText(moneda(d.getTotalReembolsado()));etiquetaIngresosNetos.setText(moneda(d.getIngresosNetos()));etiquetaIngresosManuales.setText(moneda(d.getIngresosManuales()));etiquetaEgresosManuales.setText(moneda(d.getEgresosManuales()));etiquetaResultadoOperativo.setText(moneda(d.getResultadoOperativo()));etiquetaTicketPromedio.setText(moneda(d.getTicketPromedio()));etiquetaPagosAcreditados.setText(String.valueOf(d.getCantidadPagosAcreditados()));etiquetaOcupacion.setText(d.getPorcentajeOcupacion()+" %");variacion(etiquetaVariacionReservas,d.getVariacionReservas(),d.getTotalReservas());variacion(etiquetaVariacionIngresos,d.getVariacionIngresos(),d.getIngresosAcreditados().signum());pie(graficoEstados,d.getReservasPorEstado());pie(graficoMetodos,d.getIngresosPorMetodo());barras(graficoCanchas,d.getReservasPorCancha());barras(graficoHorarios,d.getHorariosMasSolicitados());barras(graficoDias,ordenarDias(d.getDiasMasSolicitados()));barras(graficoClientes,d.getClientesFrecuentes());linea(completarMeses(d.getIngresosPorMes()));tablaCierres.getItems().setAll(d.getCierresCaja());hallazgo(hallazgoCancha,d.getReservasPorCancha(),"Sin reservas");hallazgo(hallazgoHorario,d.getHorariosMasSolicitados(),"Sin horarios");hallazgo(hallazgoDia,d.getDiasMasSolicitados(),"Sin demanda");hallazgo(hallazgoCliente,d.getClientesFrecuentes(),"Sin clientes");hallazgo(hallazgoMetodo,d.getIngresosPorMetodo(),"Sin pagos");mostrarReservasPanel(d);}
    private void mostrarReservasPanel(EstadisticasPadel d){
        reservaSolicitudes.setText(String.valueOf(d.getTotalReservas()));reservaEfectivas.setText(String.valueOf(d.getReservasEfectivas()));reservaPersonal.setText(String.valueOf(d.getReservasPersonal()));reservaWeb.setText(String.valueOf(d.getReservasWeb()));reservaPendientes.setText(String.valueOf(d.getReservasPendientes()));reservaConfirmadas.setText(String.valueOf(d.getReservasConfirmadas()));reservaCompletadas.setText(String.valueOf(d.getReservasCompletadas()));reservaCanceladas.setText(String.valueOf(d.getReservasCanceladas()));reservaAusencias.setText(String.valueOf(d.getReservasAusentes()));reservaExpiradas.setText(String.valueOf(d.getReservasExpiradas()));tasaConfirmacion.setText(porcentaje(d.getTasaConfirmacion()));tasaFinalizacion.setText(porcentaje(d.getTasaFinalizacion()));tasaCancelacion.setText(porcentaje(d.getTasaCancelacion()));tasaAusencia.setText(porcentaje(d.getTasaAusencia()));tasaExpiracionWeb.setText(porcentaje(d.getTasaExpiracionWeb()));tasaConversionWeb.setText(porcentaje(d.getConversionWeb()));
        cargarPieOrigen(d);pie(graficoCancelacionesTipo,d.getCancelacionesPorTipo());lineaEn(graficoEvolucionReservas,completarDias(d.getReservasPorDia()));cargarIncidencias(d);
    }
    private String porcentaje(BigDecimal v){return v.setScale(2,RoundingMode.HALF_UP).toPlainString()+" %";}
    private void cargarPieOrigen(EstadisticasPadel d){graficoReservasOrigen.getData().setAll(new PieChart.Data("Personal",d.getReservasPersonal()),new PieChart.Data("Web",d.getReservasWeb()));}
    private List<DatoGrafico> completarDias(List<DatoGrafico> datos){Map<String,BigDecimal> mapa=new HashMap<>();for(DatoGrafico x:datos)mapa.put(x.etiqueta(),x.valor());java.util.ArrayList<DatoGrafico> salida=new java.util.ArrayList<>();LocalDate dia=fechaDesde.getValue();while(!dia.isAfter(fechaHasta.getValue())){String clave=dia.toString();salida.add(new DatoGrafico(dia.format(DateTimeFormatter.ofPattern("dd/MM")),mapa.getOrDefault(clave,BigDecimal.ZERO)));dia=dia.plusDays(1);}return salida;}
    private void cargarIncidencias(EstadisticasPadel d){Map<String,BigDecimal> porDia=new java.util.LinkedHashMap<>();for(DatoGrafico x:d.getEvolucionIncidencias()){String dia=x.etiqueta().split("\\|")[0];porDia.merge(dia,x.valor(),BigDecimal::add);}java.util.ArrayList<DatoGrafico> datos=new java.util.ArrayList<>();for(Map.Entry<String,BigDecimal> e:porDia.entrySet()){LocalDate fecha=LocalDate.parse(e.getKey());datos.add(new DatoGrafico(fecha.format(DateTimeFormatter.ofPattern("dd/MM")),e.getValue()));}lineaEn(graficoEvolucionIncidencias,datos);}
    private void lineaEn(LineChart<String,Number> grafico,List<DatoGrafico> datos){grafico.getData().clear();XYChart.Series<String,Number> serie=new XYChart.Series<>();for(DatoGrafico x:datos)serie.getData().add(new XYChart.Data<>(x.etiqueta(),x.valor()));grafico.getData().add(serie);}

    private void variacion(Label l,BigDecimal v,int actual){if(actual>0&&v.compareTo(BigDecimal.valueOf(100))==0){l.setText("Sin base de comparación");l.getStyleClass().setAll("label","stats-trend-flat");return;}l.setText((v.signum()>0?"+":"")+v+" % frente al período anterior");l.getStyleClass().removeAll("stats-trend-up","stats-trend-down","stats-trend-flat");l.getStyleClass().add(v.signum()>0?"stats-trend-up":v.signum()<0?"stats-trend-down":"stats-trend-flat");}
    private void hallazgo(Label l,List<DatoGrafico> ds,String vacio){l.setText(ds.isEmpty()?vacio:etiqueta(ds.get(0).etiqueta())+" · "+ds.get(0).valor().stripTrailingZeros().toPlainString());}
    private List<DatoGrafico> ordenarDias(List<DatoGrafico> ds){Map<String,BigDecimal> m=new HashMap<>();for(DatoGrafico d:ds)m.put(d.etiqueta().toLowerCase(Locale.ROOT),d.valor());return List.of("Lunes","Martes","Miércoles","Jueves","Viernes","Sábado","Domingo").stream().map(x->new DatoGrafico(x,m.getOrDefault(x.toLowerCase(Locale.ROOT),BigDecimal.ZERO))).toList();}
    private List<DatoGrafico> completarMeses(List<DatoGrafico> ds){LocalDate d=fechaDesde.getValue().withDayOfMonth(1),h=fechaHasta.getValue().withDayOfMonth(1);Map<String,BigDecimal> m=new HashMap<>();for(DatoGrafico x:ds)m.put(x.etiqueta(),x.valor());java.util.ArrayList<DatoGrafico> out=new java.util.ArrayList<>();while(!d.isAfter(h)){String key=d.format(DateTimeFormatter.ofPattern("yyyy-MM"));String label=d.getMonth().getDisplayName(TextStyle.SHORT,new Locale("es","AR"))+" "+d.getYear();out.add(new DatoGrafico(label,m.getOrDefault(key,BigDecimal.ZERO)));d=d.plusMonths(1);}return out;}
    private void pie(PieChart g,List<DatoGrafico> ds){g.getData().clear();for(DatoGrafico d:ds)g.getData().add(new PieChart.Data(etiqueta(d.etiqueta()),d.valor().doubleValue()));}
    private void barras(BarChart<String,Number> g,List<DatoGrafico> ds){g.getData().clear();XYChart.Series<String,Number>s=new XYChart.Series<>();for(DatoGrafico d:ds)s.getData().add(new XYChart.Data<>(etiqueta(d.etiqueta()),d.valor()));g.getData().add(s);}
    private void linea(List<DatoGrafico> ds){graficoIngresos.getData().clear();XYChart.Series<String,Number>s=new XYChart.Series<>();for(DatoGrafico d:ds)s.getData().add(new XYChart.Data<>(d.etiqueta(),d.valor()));graficoIngresos.getData().add(s);}
    private String etiqueta(String v){if(v==null||v.isBlank())return "Sin datos";String t=v.replace('_',' ').toLowerCase(Locale.ROOT);return Character.toUpperCase(t.charAt(0))+t.substring(1);}
    private String moneda(BigDecimal v){return NumberFormat.getCurrencyInstance(new Locale("es","AR")).format(v==null?BigDecimal.ZERO:v.setScale(2,RoundingMode.HALF_UP));}
    private void carga(boolean c,String m){indicadorCarga.setVisible(c);botonActualizar.setDisable(c);etiquetaEstado.setText(m);etiquetaEstado.getStyleClass().removeAll("stats-status-ok","stats-status-error");if(!c)etiquetaEstado.getStyleClass().add("stats-status-ok");}
    private void error(String m){indicadorCarga.setVisible(false);botonActualizar.setDisable(false);etiquetaEstado.setText(m==null?"No se pudieron cargar las estadísticas.":m);etiquetaEstado.getStyleClass().removeAll("stats-status-ok","stats-status-error");etiquetaEstado.getStyleClass().add("stats-status-error");}
    @FXML private void volver(){Navegacion.mostrarDashboard(Navegacion.getUsuarioActual());}
}
