package servicio;
import java.sql.*;import java.util.*;import config.ConexionBD;import dao.*;import negocio.*;
public class GestionGruposTorneoService { private final TorneoCategoriaDAO categorias=new TorneoCategoriaDAOMySQL(); private final TorneoInscripcionDAO inscripciones=new TorneoInscripcionDAOMySQL(); private final TorneoGrupoDAO grupos=new TorneoGrupoDAOMySQL();
 public Vista cargar(long cat){try(Connection c=ConexionBD.obtenerConexion()){TorneoCategoria tc=categorias.buscar(c,cat);if(tc==null||!tc.usaFaseGrupos())throw new IllegalArgumentException("La categoria no usa fase de grupos.");List<TorneoInscripcion> conf=inscripciones.listarPorCategoria(cat).stream().filter(x->x.getEstado()==EstadoInscripcionTorneo.CONFIRMADA).toList();List<TorneoGrupo> gs=grupos.listar(c,cat);if(gs.isEmpty()){c.setAutoCommit(false);grupos.crearEstructura(c,cat,tc.getCantidadGruposTres(),tc.getCantidadGruposCuatro());c.commit();gs=grupos.listar(c,cat);}return new Vista(tc,conf,gs);}catch(SQLException e){throw new RuntimeException("No se pudo cargar la gestion de grupos.",e);}}
 public void asignar(long cat,long gid,long iid,boolean cabeza){tx(c->{validarEditable(c,cat);TorneoGrupo g=grupos.listar(c,cat).stream().filter(x->x.getId()==gid).findFirst().orElseThrow();if(g.getIntegrantes().size()>=g.getCapacidad())throw new IllegalArgumentException("El grupo esta completo.");grupos.asignar(c,gid,iid,cabeza,g.getIntegrantes().size()+1);});}
 public void quitar(long cat,long iid){tx(c->{validarEditable(c,cat);grupos.quitar(c,iid);});}
 public void sortear(long cat,Map<Long,Long> cabezas){tx(c->{TorneoCategoria tc=validarEditable(c,cat);List<TorneoInscripcion> conf=inscripciones.listarPorCategoria(cat).stream().filter(x->x.getEstado()==EstadoInscripcionTorneo.CONFIRMADA).toList();if(conf.size()!=tc.getCapacidadGrupos())throw new IllegalArgumentException("Las parejas confirmadas deben coincidir con la capacidad configurada.");List<TorneoGrupo> gs=grupos.listar(c,cat);if(cabezas.size()!=gs.size())throw new IllegalArgumentException("Selecciona un cabeza de serie por grupo.");Set<Long> ids=new HashSet<>(cabezas.values());if(ids.size()!=gs.size())throw new IllegalArgumentException("Los cabezas de serie no pueden repetirse.");grupos.limpiarAsignaciones(c,cat);int o=1;for(TorneoGrupo g:gs)grupos.asignar(c,g.getId(),cabezas.get(g.getId()),true,o++);List<Long> resto=conf.stream().map(TorneoInscripcion::getId).filter(x->!ids.contains(x)).collect(java.util.stream.Collectors.toCollection(ArrayList::new));Collections.shuffle(resto);int p=0;for(TorneoGrupo g:gs){for(int n=1;n<g.getCapacidad();n++)grupos.asignar(c,g.getId(),resto.get(p++),false,n+1);}});}
 public void confirmar(long cat,ModoAsignacionGrupoTorneo modo){tx(c->{TorneoCategoria tc=validarEditable(c,cat);List<TorneoGrupo> gs=grupos.listar(c,cat);if(gs.size()!=tc.getCantidadGrupos())throw new IllegalArgumentException("La estructura de grupos esta incompleta.");for(TorneoGrupo g:gs){if(g.getIntegrantes().size()!=g.getCapacidad())throw new IllegalArgumentException(g.getNombre()+" no esta completo.");if(modo==ModoAsignacionGrupoTorneo.SORTEO_DIRIGIDO&&g.getIntegrantes().stream().filter(TorneoGrupoIntegrante::isCabezaSerie).count()!=1)throw new IllegalArgumentException(g.getNombre()+" necesita un cabeza de serie.");}grupos.confirmar(c,cat,modo);});}
 private TorneoCategoria validarEditable(Connection c,long cat){TorneoCategoria tc=categorias.buscar(c,cat);if(tc==null||!tc.usaFaseGrupos())throw new IllegalArgumentException("Categoria no valida.");if(grupos.listar(c,cat).stream().anyMatch(TorneoGrupo::isConfirmado))throw new IllegalArgumentException("Los grupos ya fueron confirmados.");return tc;}
 private void tx(Op op){try(Connection c=ConexionBD.obtenerConexion()){c.setAutoCommit(false);try{op.run(c);c.commit();}catch(SQLException|RuntimeException e){c.rollback();throw e;}}catch(SQLException e){throw new RuntimeException("No se pudo actualizar la gestion de grupos.",e);}} private interface Op{void run(Connection c)throws SQLException;}
 public record Vista(TorneoCategoria categoria,List<TorneoInscripcion> inscripciones,List<TorneoGrupo> grupos){} }
