import { api } from './api';
type Perfil={clienteId:number;nombre:string;apellido:string;email:string;telefono:string;posicionPreferida?:'DRIVE'|'REVES'|null};
type Sesion={autenticado:boolean;vencimiento?:string|null;perfil?:Perfil|null};
const e=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
const modal=e('modalAutenticacion'); const error=e('errorAutenticacion'); let foco:HTMLElement|null=null;
function mostrarError(t=''){error.textContent=t;error.classList.toggle('hidden',!t);}
function abrir(){foco=document.activeElement as HTMLElement;modal.classList.remove('hidden');modal.classList.add('flex');document.body.style.overflow='hidden';mostrarError();setTimeout(()=>e<HTMLInputElement>('loginEmail').focus(),20);}
function cerrar(){modal.classList.add('hidden');modal.classList.remove('flex');document.body.style.overflow='';foco?.focus();}
function mostrarRecuperacion(mostrar:boolean){e('formLogin').classList.toggle('hidden',mostrar);e('formRegistro').classList.add('hidden');e('formRecuperacion').classList.toggle('hidden',!mostrar);e('tabLogin').classList.toggle('activo',!mostrar);e('tabRegistro').classList.remove('activo');e('tituloAutenticacion').textContent=mostrar?'Recuperar contraseña':'Ingresar';mostrarError();e('resultadoRecuperacion').classList.add('hidden');}
function tab(registro:boolean){e('formRecuperacion').classList.add('hidden');e('formLogin').classList.toggle('hidden',registro);e('formRegistro').classList.toggle('hidden',!registro);e('tabLogin').classList.toggle('activo',!registro);e('tabRegistro').classList.toggle('activo',registro);e('tituloAutenticacion').textContent=registro?'Crear cuenta':'Ingresar';mostrarError();}
function actualizar(s:Sesion){const ingresar=e('abrirAutenticacion');const menu=e('menuUsuario');if(s.autenticado&&s.perfil){ingresar.classList.add('hidden');menu.classList.remove('hidden');e('nombreUsuario').textContent=s.perfil.nombre;}else{ingresar.classList.remove('hidden');menu.classList.add('hidden');}window.dispatchEvent(new CustomEvent('sesion-cliente-cambiada',{detail:s}));}
async function sesion(){try{actualizar(await api<Sesion>('/auth/sesion'));}catch{actualizar({autenticado:false});}}
e('abrirAutenticacion').addEventListener('click',abrir);e('abrirRecuperacion').addEventListener('click',()=>mostrarRecuperacion(true));e('volverLogin').addEventListener('click',()=>mostrarRecuperacion(false));e('cerrarAutenticacion').addEventListener('click',cerrar);e('tabLogin').addEventListener('click',()=>tab(false));e('tabRegistro').addEventListener('click',()=>tab(true));
e('botonUsuario').addEventListener('click',()=>{const boton=e<HTMLButtonElement>('botonUsuario');const desplegable=e('desplegableUsuario');const abierto=!desplegable.classList.contains('hidden');desplegable.classList.toggle('hidden',abierto);boton.setAttribute('aria-expanded',String(!abierto));});
document.addEventListener('keydown',x=>{if(x.key==='Escape'){if(!modal.classList.contains('hidden'))cerrar();e('desplegableUsuario').classList.add('hidden');}});
e<HTMLFormElement>('formLogin').addEventListener('submit',async x=>{x.preventDefault();mostrarError();const b=e<HTMLButtonElement>('enviarLogin');const email=e<HTMLInputElement>('loginEmail').value.trim();const password=e<HTMLInputElement>('loginPassword').value;if(!email||!password)return mostrarError('Ingresá correo electrónico y contraseña.');try{b.disabled=true;b.textContent='Ingresando...';const s=await api<Sesion>('/auth/login',{method:'POST',body:JSON.stringify({email,password})});actualizar(s);cerrar();location.reload();}catch(err){mostrarError(err instanceof Error?err.message:'No se pudo iniciar sesión.');}finally{b.disabled=false;b.textContent='Ingresar';}});
e<HTMLFormElement>('formRegistro').addEventListener('submit',async x=>{x.preventDefault();mostrarError();const b=e<HTMLButtonElement>('enviarRegistro');const v=(id:string)=>e<HTMLInputElement|HTMLSelectElement>(id).value.trim();const password=e<HTMLInputElement>('registroPassword').value;const repetir=e<HTMLInputElement>('registroPasswordRepetido').value;try{if(!v('registroNombre'))throw new Error('El nombre es obligatorio.');if(!v('registroApellido'))throw new Error('El apellido es obligatorio.');if(!/^\d{7,10}$/.test(v('registroDocumento').replace(/\D/g,'')))throw new Error('El documento debe contener entre 7 y 10 números.');if(!/^[0-9+()\-\s]{6,30}$/.test(v('registroTelefono')))throw new Error('El teléfono contiene caracteres no válidos.');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v('registroEmail')))throw new Error('El correo electrónico no tiene un formato válido.');if(password.length<8)throw new Error('La contraseña debe tener al menos 8 caracteres.');if(password!==repetir)throw new Error('Las contraseñas no coinciden.');const posicionPreferida=v('registroPosicion')||null;b.disabled=true;b.textContent='Creando cuenta...';const s=await api<Sesion>('/auth/registro',{method:'POST',body:JSON.stringify({nombre:v('registroNombre'),apellido:v('registroApellido'),documento:v('registroDocumento').replace(/\D/g,''),telefono:v('registroTelefono'),email:v('registroEmail'),password,posicionPreferida})});actualizar(s);cerrar();location.reload();}catch(err){mostrarError(err instanceof Error?err.message:'No se pudo crear la cuenta.');}finally{b.disabled=false;b.textContent='Crear cuenta';}});

e<HTMLFormElement>('formRecuperacion').addEventListener('submit',async x=>{x.preventDefault();mostrarError();const b=e<HTMLButtonElement>('enviarRecuperacion');const email=e<HTMLInputElement>('recuperacionEmail').value.trim();const resultado=e('resultadoRecuperacion');try{if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new Error('Ingresá un correo electrónico válido.');b.disabled=true;b.textContent='Enviando...';const r=await api<{mensaje:string;enlacePrueba?:string|null}>('/auth/recuperar',{method:'POST',body:JSON.stringify({email})});let contenido='<strong class="block">'+r.mensaje+'</strong>';if(r.enlacePrueba){const u=new URL(r.enlacePrueba,location.origin);const token=u.searchParams.get('recuperar');if(token)contenido+='<a class="mt-3 inline-flex rounded-lg border border-emerald-300/50 px-4 py-2 font-black text-white" href="/restablecer?token='+encodeURIComponent(token)+'">Abrir enlace de prueba</a>';}resultado.innerHTML=contenido;resultado.classList.remove('hidden');}catch(err){mostrarError(err instanceof Error?err.message:'No se pudo solicitar la recuperación.');}finally{b.disabled=false;b.textContent='Enviar instrucciones';}});
e('cerrarSesion').addEventListener('click',async()=>{const b=e<HTMLButtonElement>('cerrarSesion');try{b.disabled=true;b.textContent='Cerrando...';await api('/auth/logout',{method:'POST'});actualizar({autenticado:false});location.href='/';}catch(err){b.disabled=false;b.textContent='Cerrar sesión';alert(err instanceof Error?err.message:'No se pudo cerrar la sesión.');}});
const tokenRecuperacion=new URLSearchParams(location.search).get('recuperar');if(tokenRecuperacion){location.replace(`/restablecer?token=${encodeURIComponent(tokenRecuperacion)}`);}else{sesion();}
