import { api, type CompetenciaCategoriaPublica, type GrupoTorneoPublico, type PartidoCuadroPublico, type PartidoGrupoPublico, type TorneoDetalle } from './api';
import { etiqueta, fecha, rangoFechas } from './formatos';
type Vista='resumen'|'posiciones'|'partidos'|'cuadro';
const VISTAS:Vista[]=['resumen','posiciones','partidos','cuadro'];
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));
const etapa=(v:string)=>({PREPARACION:'Preparación',GRUPOS_EN_PREPARACION:'Grupos en preparación',GRUPOS_EN_CURSO:'Fase de grupos',GRUPOS_FINALIZADOS:'Grupos finalizados',DESEMPATE_PENDIENTE:'Desempate pendiente',ELIMINATORIAS:'Etapa eliminatoria',FINALIZADA:'Competencia finalizada'} as Record<string,string>)[v]||etiqueta(v);
const formato=(v:string)=>v==='GRUPOS_ELIMINACION'?'Grupos + eliminación':'Eliminación directa';
const pareja=(p?:{jugadores:string[]}|null)=>p?.jugadores?.length?p.jugadores.map(esc).join(' / '):'Por definir';
const agenda=(p:{fecha?:string|null;horaInicio?:string|null;cancha?:string|null;estado?:string;resultado?:string|null})=>p.fecha?fecha(p.fecha)+(p.horaInicio?' · '+p.horaInicio.slice(0,5):'')+(p.cancha?' · '+esc(p.cancha):''):p.estado==='FINALIZADO'&&p.resultado?'':p.estado==='FINALIZADO'?'Resultado confirmado':'Horario por definir';
let torneo:TorneoDetalle|null=null,competencia:CompetenciaCategoriaPublica|null=null,vista:Vista='resumen',grupoId=0,instancia='todos',ronda=0;
function parametros(reemplazar=false){if(!torneo||!competencia)return;const u=new URL(location.href);u.searchParams.set('torneo',String(torneo.id));u.searchParams.set('categoria',String(competencia.categoria.id));u.searchParams.set('vista',vista);u.searchParams.delete('seccion');if(grupoId)u.searchParams.set('grupo',String(grupoId));else u.searchParams.delete('grupo');if(vista==='partidos'&&instancia!=='todos')u.searchParams.set('instancia',instancia);else u.searchParams.delete('instancia');history[reemplazar?'replaceState':'pushState']({torneo:torneo.id,categoria:competencia.categoria.id,vista,instancia},'',u)}
function vacio(t:string,p:string){return '<div class="f4-empty"><b>'+esc(t)+'</b><p>'+esc(p)+'</p></div>'}
function tarjetaPartido(p:PartidoGrupoPublico|PartidoCuadroPublico,kicker:string){const g=p.ganadoraInscripcionId,g1=!!p.pareja1&&g===p.pareja1.inscripcionId,g2=!!p.pareja2&&g===p.pareja2.inscripcionId;return '<article class="f4-match"><header><span>'+esc(kicker)+'</span><i class="state-'+esc(p.estado.toLowerCase())+'">'+esc(etiqueta(p.estado))+'</i></header><div class="f4-teams"><div class="'+(g1?'winner':'')+'"><b>'+pareja(p.pareja1)+'</b><em>'+(g1?'Ganador':'')+'</em></div><div class="'+(g2?'winner':'')+'"><b>'+pareja(p.pareja2)+'</b><em>'+(g2?'Ganador':'')+'</em></div></div><footer><strong>'+esc(p.resultado||etiqueta(p.estado))+'</strong><small class="'+(agenda(p)?'':'hidden')+'">'+agenda(p)+'</small></footer></article>'}
function selectorCategoria(){if(!torneo||!competencia)return '';if(torneo.categorias.length===1){const c=competencia,total=c.resumen.partidosGrupos+c.resumen.partidosEliminatorios,fin=c.resumen.partidosGruposFinalizados+c.resumen.partidosEliminatoriosFinalizados;return '<aside class="f4-hero-facts"><span><small>Grupos</small><b>'+c.grupos.length+'</b></span><span><small>Clasificados</small><b>'+c.categoria.clasificadosProyectados+'</b></span><span><small>Partidos</small><b>'+fin+' / '+total+'</b></span></aside>'}return '<aside><small>Categoría</small><div class="f4-category-selector">'+torneo.categorias.map(c=>'<button type="button" data-f4-category="'+c.id+'" class="'+(competencia?.categoria.id===c.id?'active':'')+'"><span>'+esc(c.nombre)+'</span><small>'+esc(etiqueta(c.rama))+'</small></button>').join('')+'</div></aside>'}
function nav(){return '<nav class="f4-nav" aria-label="Centro competitivo">'+VISTAS.map(x=>'<button type="button" data-f4-view="'+x+'" class="'+(vista===x?'active':'')+'">'+({resumen:'Resumen',posiciones:'Posiciones',partidos:'Partidos',cuadro:'Cuadro'} as Record<Vista,string>)[x]+'</button>').join('')+'</nav>'}
function resumen(){if(!competencia)return '';const c=competencia,total=c.resumen.partidosGrupos+c.resumen.partidosEliminatorios,fin=c.resumen.partidosGruposFinalizados+c.resumen.partidosEliminatoriosFinalizados,pct=total?Math.round(fin/total*100):0,todos=[...c.grupos.flatMap(g=>g.partidos.map(p=>({p,k:g.nombre}))),...(c.eliminatorias?.fases||[]).flatMap(f=>f.partidos.map(p=>({p,k:etiqueta(f.nombre)})))],proximos=todos.filter(x=>x.p.estado!=='FINALIZADO').slice(0,3),ultimos=todos.filter(x=>x.p.estado==='FINALIZADO').slice(-3).reverse();return '<div class="f4-status-grid"><article><small>Etapa actual</small><b>'+esc(etapa(c.resumen.etapa))+'</b><p>La competencia se actualiza con cada resultado publicado.</p></article><article><small>Formato</small><b>'+esc(formato(c.categoria.formatoCompetencia))+'</b><p>'+(c.grupos.length?c.grupos.length+' grupos · '+c.categoria.clasificadosProyectados+' clasificados previstos':'Llave eliminatoria directa')+'</p></article><article><small>Progreso</small><b>'+fin+' de '+total+' partidos</b><span><i style="width:'+pct+'%"></i></span><p>'+pct+'% completado</p></article></div><div class="f4-dashboard"><section><header><p class="site-kicker">Agenda competitiva</p><h3>Próximos partidos</h3></header><div class="f4-match-grid compact">'+(proximos.map(x=>tarjetaPartido(x.p,x.k)).join('')||vacio('Sin partidos programados','La organización todavía no publicó próximos encuentros.'))+'</div></section><section><header><p class="site-kicker">Última actividad</p><h3>Resultados recientes</h3></header><div class="f4-match-grid compact">'+(ultimos.map(x=>tarjetaPartido(x.p,x.k)).join('')||vacio('Sin resultados','Los resultados aparecerán al finalizar los primeros partidos.'))+'</div></section></div>'}
function tabla(g:GrupoTorneoPublico){return '<section class="f4-standings"><header><div><p class="site-kicker">Clasificación del grupo</p><h3>'+esc(g.nombre)+' · Tabla de posiciones</h3></div><span>'+esc(g.desempatePendiente?'Desempate pendiente':g.posicionesDefinitivas?'Posiciones definitivas':'Posiciones provisorias')+'</span></header><div class="f4-table-wrap"><table><thead><tr><th>#</th><th>Pareja</th><th>PJ</th><th>PG</th><th>PP</th><th>Sets</th><th>DS</th><th>Games</th><th>DG</th><th>Estado</th></tr></thead><tbody>'+g.posiciones.map(p=>'<tr class="'+(p.estado==='CLASIFICADO'?'qualified':p.estado==='DESEMPATE_PENDIENTE'?'tie':'')+'"><td><b>'+p.posicion+'</b></td><td>'+esc(p.pareja)+'</td><td>'+p.partidosJugados+'</td><td>'+p.partidosGanados+'</td><td>'+p.partidosPerdidos+'</td><td>'+p.setsGanados+'-'+p.setsPerdidos+'</td><td>'+p.diferenciaSets+'</td><td>'+p.gamesGanados+'-'+p.gamesPerdidos+'</td><td>'+p.diferenciaGames+'</td><td><span class="f4-position-state state-'+esc(p.estado.toLowerCase())+'">'+esc(etiqueta(p.estado))+'</span></td></tr>').join('')+'</tbody></table></div><p class="f4-table-legend"><b>PJ</b> jugados · <b>PG</b> ganados · <b>PP</b> perdidos · <b>DS</b> diferencia de sets · <b>DG</b> diferencia de games</p></section>'}
function posiciones(){if(!competencia)return '';if(!competencia.grupos.length)return vacio('Sin fase de grupos','Esta categoría utiliza eliminación directa.');const g=competencia.grupos.find(x=>x.id===grupoId)||competencia.grupos[0];grupoId=g.id;return '<div class="f4-group-tabs">'+competencia.grupos.map(x=>'<button type="button" data-f4-group="'+x.id+'" class="'+(x.id===g.id?'active':'')+'">'+esc(x.nombre)+'</button>').join('')+'</div>'+tabla(g)}
type Bloque={id:string;nombre:string;items:string[]};
function tituloPartidos(bloques:Bloque[]){if(instancia==='todos')return {titulo:'Todos los partidos',texto:'Horarios, canchas y resultados organizados por instancia.'};const b=bloques.find(x=>x.id===instancia);if(!b)return {titulo:'Todos los partidos',texto:'Horarios, canchas y resultados organizados por instancia.'};if(b.id.startsWith('grupo-'))return {titulo:'Partidos de '+b.nombre,texto:'Calendario y resultados de la fase de grupos.'};return {titulo:b.nombre==='Final'?'Final':'Partidos de '+b.nombre,texto:'Cruces, programación y resultados de esta instancia.'}}
function claseCantidad(n:number){return n===1?'count-1':n===2?'count-2':n===4?'count-4':'count-many'}
function bloquesPartidos():Bloque[]{if(!competencia)return [];return [...competencia.grupos.filter(g=>g.partidos.length).map(g=>({id:'grupo-'+g.id,nombre:g.nombre,items:g.partidos.map((p,i)=>tarjetaPartido(p,'Partido '+(i+1)))})),...(competencia.eliminatorias?.fases||[]).filter(f=>f.nombre!=='GRUPOS'&&f.partidos.length).map(f=>({id:'fase-'+f.nombre.toLowerCase(),nombre:etiqueta(f.nombre),items:f.partidos.map(p=>tarjetaPartido(p,p.fase==='FINAL'?'Final':'Partido '+p.orden))}))]}
function partidos(){const bloques=bloquesPartidos();if(!bloques.length)return vacio('Todavía no hay partidos','La programación aparecerá cuando la organización genere los encuentros.');const visibles=instancia==='todos'?bloques:bloques.filter(b=>b.id===instancia),enc=tituloPartidos(bloques);return '<section class="f4-section-head"><div><p class="site-kicker">Calendario y resultados</p><h3>'+esc(enc.titulo)+'</h3></div><p>'+esc(enc.texto)+'</p></section><div class="f4-phase-index" role="tablist" aria-label="Filtrar partidos por instancia"><button type="button" role="tab" aria-selected="'+(instancia==='todos')+'" data-f4-phase="todos" class="'+(instancia==='todos'?'active':'')+'">Todos <b>'+bloques.reduce((a,b)=>a+b.items.length,0)+'</b></button>'+bloques.map(b=>'<button type="button" role="tab" aria-selected="'+(instancia===b.id)+'" data-f4-phase="'+esc(b.id)+'" class="'+(instancia===b.id?'active':'')+'">'+esc(b.nombre)+' <b>'+b.items.length+'</b></button>').join('')+'</div><div class="f4-phase-list">'+visibles.map(b=>'<section class="f4-phase-section"><header><h4>'+esc(b.nombre)+' <span>'+b.items.length+' '+(b.items.length===1?'partido':'partidos')+'</span></h4></header><div class="f4-match-grid '+claseCantidad(b.items.length)+'">'+b.items.join('')+'</div></section>').join('')+'</div>'}
function cuadro(){if(!competencia)return '';const c=competencia.eliminatorias,fases=(c?.fases||[]).filter(f=>f.nombre!=='GRUPOS');if(!fases.length)return vacio('Cuadro pendiente de publicación','La llave aparecerá cuando la organización confirme las eliminatorias.');ronda=Math.max(0,Math.min(ronda,fases.length-1));return (c?.campeona?'<section class="f4-champion"><small>★ Pareja campeona</small><h3>'+pareja(c.campeona)+'</h3><p>'+esc(c.campeona.resultadoFinal||'Final disputada')+'</p></section>':'')+'<div class="f4-round-tabs">'+fases.map((f,i)=>'<button type="button" data-f4-round="'+i+'" class="'+(i===ronda?'active':'')+'">'+esc(etiqueta(f.nombre))+'</button>').join('')+'</div><div class="f4-rounds">'+fases.map((f,i)=>'<section class="f4-round '+(i===ronda?'mobile-active':'')+'"><header><h3>'+esc(etiqueta(f.nombre))+'</h3><span>'+f.partidos.length+' '+(f.partidos.length===1?'partido':'partidos')+'</span></header><div>'+f.partidos.map(p=>tarjetaPartido(p,p.fase==='FINAL'?'Final':'Partido '+p.orden)).join('')+'</div></section>').join('')+'</div><nav class="f4-round-pager"><button type="button" data-f4-round-step="-1" '+(ronda===0?'disabled':'')+'>‹ Anterior</button><span>'+(ronda+1)+' / '+fases.length+'</span><button type="button" data-f4-round-step="1" '+(ronda===fases.length-1?'disabled':'')+'>Siguiente ›</button></nav>'}
function alinearVista(){requestAnimationFrame(()=>{const nav=document.querySelector<HTMLElement>('.f4-nav');if(!nav)return;const header=Number.parseFloat(getComputedStyle(document.documentElement).getPropertyValue('--header-height'))||76;const top=nav.getBoundingClientRect().top;if(top<header-2||top>header+160)scrollTo({top:scrollY+top-header-4,behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})})}
function centrarFiltroActivo(){requestAnimationFrame(()=>document.querySelector<HTMLElement>('.f4-phase-index .active')?.scrollIntoView({block:'nearest',inline:'center',behavior:'smooth'}))}
function contenido(){return vista==='resumen'?resumen():vista==='posiciones'?posiciones():vista==='partidos'?partidos():cuadro()}
function render(){if(!torneo||!competencia)return;const host=document.getElementById('detalleTorneoHost');if(!host)return;host.innerHTML='<article class="f4-center"><div class="f4-topbar"><button type="button" data-f4-back>← Volver al torneo</button><button type="button" data-share-tournament>Compartir</button></div><header class="f4-hero"><div><span>'+esc(etapa(competencia.resumen.etapa))+'</span><p class="site-kicker">Centro competitivo</p><h1>'+esc(competencia.categoria.nombre)+' · '+esc(etiqueta(competencia.categoria.rama))+'</h1><p>'+esc(torneo.nombre)+' · '+esc(rangoFechas(torneo.fechaInicio,torneo.fechaFin))+' · '+esc(formato(competencia.categoria.formatoCompetencia))+'</p></div>'+selectorCategoria()+'</header>'+nav()+'<main class="f4-content">'+contenido()+'</main></article>';document.title=competencia.categoria.nombre+' · '+torneo.nombre+' | Pádel Reservas'}
export async function abrirCentroCompetitivo(t:TorneoDetalle,categoriaId:number,v:Vista='resumen',actualizar=true){torneo=t;vista=VISTAS.includes(v)?v:'resumen';const q=new URLSearchParams(location.search);grupoId=Number(q.get('grupo'))||0;instancia=q.get('instancia')||'todos';const host=document.getElementById('detalleTorneoHost');if(host)host.innerHTML='<div class="f4-loading">Cargando centro competitivo...</div>';try{competencia=await api<CompetenciaCategoriaPublica>('/torneos/categorias/'+categoriaId+'/competencia');if(!grupoId)grupoId=competencia.grupos[0]?.id||0;if(!bloquesPartidos().some(b=>b.id===instancia))instancia='todos';render();parametros(!actualizar);scrollTo({top:0,behavior:'auto'})}catch(e){if(host)host.innerHTML='<div class="competition-error"><b>No pudimos cargar la competencia</b><p>'+esc(e instanceof Error?e.message:'Intentá nuevamente.')+'</p></div>'}}
export function restaurarCentroDesdeUrl(){if(!torneo||!competencia)return false;const q=new URLSearchParams(location.search),cat=Number(q.get('categoria'));if(cat!==competencia.categoria.id)return false;vista=VISTAS.includes(q.get('vista') as Vista)?q.get('vista') as Vista:'resumen';grupoId=Number(q.get('grupo'))||competencia.grupos[0]?.id||0;instancia=q.get('instancia')||'todos';if(!bloquesPartidos().some(b=>b.id===instancia))instancia='todos';render();return true}
export function manejarCentroCompetitivoClick(target:HTMLElement){const back=target.closest('[data-f4-back]');if(back&&torneo){competencia=null;const u=new URL(location.href);['categoria','vista','grupo','instancia'].forEach(x=>u.searchParams.delete(x));u.searchParams.set('seccion','categorias');history.pushState({torneo:torneo.id},'',u);dispatchEvent(new CustomEvent('f4-back',{detail:{torneo}}));return true}const cat=target.closest<HTMLButtonElement>('[data-f4-category]');if(cat&&torneo){abrirCentroCompetitivo(torneo,Number(cat.dataset.f4Category),vista);return true}const view=target.closest<HTMLButtonElement>('[data-f4-view]');if(view){vista=view.dataset.f4View as Vista;if(vista!=='partidos')instancia='todos';render();parametros();alinearVista();return true}const group=target.closest<HTMLButtonElement>('[data-f4-group]');if(group){grupoId=Number(group.dataset.f4Group);render();parametros();return true}const phase=target.closest<HTMLButtonElement>('[data-f4-phase]');if(phase){instancia=phase.dataset.f4Phase||'todos';render();parametros();centrarFiltroActivo();alinearVista();return true}const rt=target.closest<HTMLButtonElement>('[data-f4-round]');if(rt){ronda=Number(rt.dataset.f4Round)||0;render();return true}const step=target.closest<HTMLButtonElement>('[data-f4-round-step]');if(step){ronda+=Number(step.dataset.f4RoundStep)||0;render();return true}return false}
export const centroActivo=()=>Boolean(competencia);
