import { api, type Complejo } from './api';
import { etiqueta, fecha, fechaHora, hora, moneda } from './formatos';
type Reserva={reservaId?:number;solicitudId?:number;codigoSeguimiento?:string|null;estado:string;cancha:string;fecha:string;horaInicio:string;horaFin:string;precioTotal:number;totalAcreditado:number;importeSenia:number;saldoPendiente:number;vencimiento?:string|null;fechaExpiracion?:string|null;fechaCancelacion?:string|null;fechaCreacion?:string|null;pendiente:boolean;confirmada:boolean;expirada:boolean;moneda:string;mensaje:string};
type Historial={proximas:Reserva[];anteriores:Reserva[];total:number}; type Perfil={clienteId:number;nombre:string;apellido:string;documento:string;telefono:string;email?:string};
const el=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
let complejo:Complejo|null=null,historialActual:Historial={proximas:[],anteriores:[],total:0},tabActual:'proximas'|'anteriores'='proximas',codigoActivo='',temporizador:number|undefined,intervalo:number|undefined,autenticado=false,cargaVisible:number|undefined,limiteHistorial=8,filtroHistorial='TODOS',busquedaHistorial='';
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c));
const uuid=(v:string)=>/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(v.trim());
const movimientoReducido=()=>window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const codigoCorto=(codigo:string)=>codigo.length>17?`${codigo.slice(0,8)}…${codigo.slice(-4)}`:codigo;
const horaActualizacion=()=>new Intl.DateTimeFormat('es-AR',{hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).format(new Date());
const fechaContextual=(valor:string)=>{const d=new Date(`${valor}T00:00:00`),h=new Date(),manana=new Date();manana.setDate(h.getDate()+1);const misma=(a:Date,b:Date)=>a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate();if(misma(d,h))return'Hoy';if(misma(d,manana))return'Mañana';return new Intl.DateTimeFormat('es-AR',{day:'numeric',month:'long',...(d.getFullYear()!==h.getFullYear()?{year:'numeric'}:{})}).format(d)};

const fechaReserva=(r:Reserva,usarContexto:boolean)=>usarContexto?fechaContextual(r.fecha):new Intl.DateTimeFormat('es-AR',{day:'numeric',month:'long',...(new Date(`${r.fecha}T00:00:00`).getFullYear()!==new Date().getFullYear()?{year:'numeric'}:{})}).format(new Date(`${r.fecha}T00:00:00`));
const iconoEstado=(estado:string)=>{const iconos:Record<string,string>={COMPLETADA:'<path d="m7 12 3 3 7-7"/><circle cx="12" cy="12" r="9"/>',CANCELADA:'<path d="m9 9 6 6m0-6-6 6"/><circle cx="12" cy="12" r="9"/>',EXPIRADA:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',AUSENTE:'<circle cx="12" cy="8" r="3"/><path d="M6.5 19c.8-3 2.6-5 5.5-5s4.7 2 5.5 5"/>',CONFIRMADA:'<path d="m7 12 3 3 7-7"/><circle cx="12" cy="12" r="9"/>',PENDIENTE:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>'};return `<svg viewBox="0 0 24 24" aria-hidden="true">${iconos[estado]||iconos.PENDIENTE}</svg>`};
function estadoVisual(r:Reserva){const mapa:Record<string,[string,string,string]>= {PENDIENTE:['Esperando seña','pending','La reserva temporal necesita alcanzar la seña requerida.'],CONFIRMADA:['Confirmada','confirmed','La cancha ya está reservada para vos.'],COMPLETADA:['Completada','completed','El turno finalizó correctamente.'],CANCELADA:['Cancelada','cancelled','La reserva fue cancelada.'],EXPIRADA:['Expirada','expired','El plazo terminó y el turno fue liberado.'],AUSENTE:['Ausente','absent','La reserva fue cerrada como ausencia.']};const x=mapa[r.estado]||[etiqueta(r.estado),'neutral',r.mensaje||''];return{texto:x[0],clase:x[1],ayuda:x[2]}}
const faltaSenia=(r:Reserva)=>Math.max(0,Number(r.importeSenia||0)-Number(r.totalAcreditado||0));
function progresoSenia(r:Reserva){const requerida=Number(r.importeSenia||0);return requerida<=0?100:Math.max(0,Math.min(100,Math.round(Number(r.totalAcreditado||0)/requerida*100)))}
function contadorMarkup(r:Reserva){if(!r.pendiente||!r.vencimiento)return'';return `<div class="booking-v2-countdown" data-vencimiento="${esc(r.vencimiento)}"><small>Reserva temporal activa</small><strong data-contador>--:--</strong><span>Vence ${fechaHora(r.vencimiento)}</span></div>`}
function codigoMarkup(r:Reserva){const c=r.codigoSeguimiento||'';return c?`<div class="booking-v2-code"><small>Código</small><div><strong title="${esc(c)}">${esc(codigoCorto(c))}</strong><button class="copiar-codigo" data-copiar="${esc(c)}" data-texto="Copiado" type="button">Copiar</button></div></div>`:`<div class="booking-v2-code"><small>Reserva administrativa</small><strong>#${r.reservaId||'-'}</strong></div>`}
function pago(r:Reserva){if(!r.pendiente||!complejo?.pagoTransferenciaDisponible)return'';const alias=complejo.pagoAlias||'',wa=(complejo.whatsapp||'').replace(/\D/g,''),texto=encodeURIComponent(`Hola, informo el pago de la seña. Solicitud #${r.solicitudId||r.reservaId}. ${r.cancha}, ${fecha(r.fecha)}, ${hora(r.horaInicio)}. Importe: ${moneda(faltaSenia(r),r.moneda)}.`);return `<section class="booking-v2-payment"><header><div><small>Acción necesaria</small><h4>Transferí la seña y esperá su acreditación</h4></div><strong>${moneda(faltaSenia(r),r.moneda)}</strong></header><div class="booking-v2-payment-grid"><span><small>Alias</small><b>${esc(alias||'-')}</b></span><span><small>Titular</small><b>${esc(complejo.pagoTitular||'-')}</b></span><span><small>Entidad</small><b>${esc(complejo.pagoEntidad||'-')}</b></span></div>${complejo.pagoInstrucciones?`<p>${esc(complejo.pagoInstrucciones)}</p>`:''}<div class="booking-v2-payment-actions"><button class="copiar-codigo" data-copiar="${esc(alias)}" data-texto="Alias copiado" type="button">Copiar alias</button>${wa?`<a href="https://wa.me/${wa}?text=${texto}" target="_blank" rel="noopener">Informar por WhatsApp</a>`:''}</div><p class="booking-v2-payment-note">La reserva se confirmará automáticamente cuando la seña sea acreditada.</p></section>`}
function finanzas(r:Reserva,compacta:boolean){if(compacta)return `<div class="booking-v2-history-money"><span>Total <b>${moneda(r.precioTotal,r.moneda)}</b></span><span>Acreditado <b>${moneda(r.totalAcreditado,r.moneda)}</b></span></div>`;if(r.pendiente){const p=progresoSenia(r);return `<div class="booking-v2-finance pending"><span><small>Seña requerida</small><strong>${moneda(r.importeSenia,r.moneda)}</strong></span><span><small>Acreditado para confirmar</small><strong>${moneda(Math.min(Number(r.totalAcreditado||0),Number(r.importeSenia||0)),r.moneda)}</strong></span><span class="priority"><small>Falta para confirmar</small><strong>${moneda(faltaSenia(r),r.moneda)}</strong></span><span><small>Total del turno</small><strong>${moneda(r.precioTotal,r.moneda)}</strong></span></div><div class="booking-v2-progress"><div><span style="width:${p}%"></span></div><small>${p}% de la seña acreditada</small></div>`}return `<div class="booking-v2-finance confirmed"><span class="accent"><small>Seña acreditada</small><strong>${moneda(r.totalAcreditado,r.moneda)}</strong></span><span><small>Saldo del turno</small><strong>${moneda(r.saldoPendiente,r.moneda)}</strong></span><span><small>Total</small><strong>${moneda(r.precioTotal,r.moneda)}</strong></span></div>`}
function mensajeReserva(r:Reserva,s:{ayuda:string}){if(r.confirmada)return r.saldoPendiente>0?`Tu reserva está confirmada. Queda un saldo de ${moneda(r.saldoPendiente,r.moneda)} para completar según las condiciones del complejo.`:'Tu reserva está confirmada y no registra saldo pendiente.';return s.ayuda}
function tarjeta(r:Reserva,compacta=false,cuenta=false,destacada=false,secundaria=false){const s=estadoVisual(r),fechaVisible=fechaReserva(r,!compacta),nota=!secundaria&&!compacta?`<div class="booking-v2-message state-${s.clase}"><span>${iconoEstado(r.estado)}</span><div><b>${r.confirmada?'Reserva asegurada':s.texto}</b><small>${mensajeReserva(r,s)}</small></div></div>`:'',historial=compacta?`<div class="booking-v2-history-context state-${s.clase}"><span>${iconoEstado(r.estado)}</span><p>${s.ayuda}</p><a href="/reservar">Reservar nuevamente <b>→</b></a></div>`:'';return `<article class="booking-v2-card ${compacta?'compact history-card':''} ${destacada?'featured':''} ${secundaria?'secondary':''}" data-state="${s.clase}"><div class="booking-v2-card-accent"></div><header><div><div class="booking-v2-badges">${destacada?'<span class="booking-v2-next">Próximo turno</span>':''}<span class="booking-status ${s.clase}">${s.texto}</span></div><h3>${esc(r.cancha)}</h3><p>${fechaVisible} · ${hora(r.horaInicio)} a ${hora(r.horaFin)}</p></div>${codigoMarkup(r)}</header>${contadorMarkup(r)}${finanzas(r,compacta)}${nota}${historial}${!compacta?`${pago(r)}${cuenta?'':`<footer class="booking-v2-actions query-actions"><a href="/reservar">Reservar otra cancha</a></footer>`}`:''}</article>`}
function enlazar(c:HTMLElement){enlazarCopias(c);c.querySelectorAll<HTMLButtonElement>('.actualizar-una').forEach(b=>b.addEventListener('click',()=>consultar(b.dataset.codigo||'',b,true)));iniciarContadores(c)}
function enlazarCopias(c:HTMLElement){c.querySelectorAll<HTMLButtonElement>('.copiar-codigo').forEach(b=>b.addEventListener('click',async()=>{const original=b.textContent;try{await navigator.clipboard.writeText(b.dataset.copiar||'');b.textContent=b.dataset.texto||'Copiado';b.classList.add('copiado')}catch{b.textContent='No se pudo copiar';b.classList.add('error-copia')}setTimeout(()=>{b.textContent=original;b.classList.remove('copiado','error-copia')},1500)}))}
function iniciarContadores(c=document.body){if(temporizador)clearInterval(temporizador);const actualizar=()=>{c.querySelectorAll<HTMLElement>('[data-vencimiento]').forEach(n=>{const destino=new Date(n.dataset.vencimiento||'').getTime(),salida=n.querySelector<HTMLElement>('[data-contador]');if(!salida||Number.isNaN(destino))return;const d=destino-Date.now();if(d<=0){salida.textContent='00:00';n.classList.add('expired-local');return}const m=Math.floor(d/60000),s=Math.floor((d%60000)/1000);salida.textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`})};actualizar();temporizador=window.setInterval(actualizar,1000)}
function error(id:string,texto=''){const n=el(id);n.textContent=texto;n.classList.toggle('hidden',!texto)}
function validarCodigo(codigo:string,idError:string,input:HTMLInputElement){if(!codigo){error(idError,'Ingresá el código de seguimiento.');input.focus({preventScroll:true});return false}if(!uuid(codigo)){error(idError,'El código no tiene un formato válido. Copialo completo e intentá otra vez.');input.focus({preventScroll:true});return false}error(idError);return true}
async function consultar(codigo:string,boton?:HTMLButtonElement,silenciosa=false){if(!codigo)return;codigoActivo=codigo;const r=el('resultadoSeguimiento');if(!silenciosa){r.classList.remove('hidden');r.innerHTML='<div class="bookings-loading"><span></span><div><strong>Consultando reserva</strong><p>Buscando el estado más reciente.</p></div></div>';r.scrollIntoView({behavior:movimientoReducido()?'auto':'smooth',block:'start'})}try{if(boton){boton.disabled=true;boton.textContent='Actualizando...'}const reserva=await api<Reserva>(`/solicitudes/${encodeURIComponent(codigo)}`);r.classList.remove('hidden');r.innerHTML=tarjeta(reserva);enlazar(r);localStorage.setItem('padel.solicitud.codigo',codigo);configurarActualizacion(reserva)}catch(e){if(!silenciosa)r.innerHTML=`<div class="bookings-query-failed"><strong>No pudimos encontrar la reserva</strong><p>${esc(e instanceof Error?e.message:'Revisá el código e intentá nuevamente.')}</p></div>`}finally{if(boton){boton.disabled=false;boton.textContent=boton.id==='consultarSeguimiento'?'Consultar reserva':boton.classList.contains('actualizar-una')?'Actualizar estado':'Consultar'}}}
function configurarActualizacion(r:Reserva){if(intervalo)clearInterval(intervalo);if(r.pendiente&&r.codigoSeguimiento)intervalo=window.setInterval(()=>{if(document.visibilityState==='visible')consultar(r.codigoSeguimiento||'',undefined,true)},30000)}
function metricas(h:Historial){const p=h.proximas.filter(x=>x.pendiente).length,c=h.proximas.filter(x=>x.confirmada).length,cal='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 3v3M17 3v3M4 9h16M5 5h14a1 1 0 0 1 1 1v13a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V6a1 1 0 0 1 1-1Z"/></svg>',espera='<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></svg>',check='<svg viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path d="m8 12 2.7 2.7L16.5 9"/></svg>';el('metricasReservas').innerHTML=`<article><i>${cal}</i><small>Próximas</small><strong>${h.proximas.length}</strong><span>turnos por jugar</span></article><article class="${p?'attention':'quiet'}"><i>${espera}</i><small>Esperando seña</small><strong>${p}</strong><span>${p?'requieren seguimiento':'sin acciones pendientes'}</span></article><article><i>${check}</i><small>Confirmadas</small><strong>${c}</strong><span>listas para jugar</span></article>`;el('cantidadProximas').textContent=String(h.proximas.length);el('cantidadAnteriores').textContent=String(h.anteriores.length)}
function renderLista(){const enHistorial=tabActual==='anteriores',historial=historialActual.anteriores.filter(r=>(filtroHistorial==='TODOS'||r.estado===filtroHistorial)&&(!busquedaHistorial||r.cancha.toLocaleLowerCase('es').includes(busquedaHistorial))),lista=enHistorial?historial.slice(0,limiteHistorial):historialActual.proximas,c=el('reservasCuenta'),tools=el('filtrosHistorial'),acciones=el('accionesHistorial');tools.classList.toggle('hidden',!enHistorial);acciones.classList.toggle('hidden',!enHistorial||historial.length===0);el('cantidadResultadosHistorial').textContent=String(historial.length);if(!lista.length){c.innerHTML=`<div class="bookings-empty"><span>${enHistorial?'⌕':'⌁'}</span><h3>${enHistorial?'No encontramos reservas':'No tenés próximas reservas'}</h3><p>${enHistorial?'Probá con otro estado o nombre de cancha.':'Cuando reserves una cancha aparecerá acá con su seguimiento y pago.'}</p>${enHistorial?'':'<a class="btn btn-primary" href="/reservar">Reservar cancha</a>'}</div>`;acciones.classList.add('hidden');return}c.innerHTML=lista.map((r,i)=>tarjeta(r,enHistorial,true,!enHistorial&&i===0,!enHistorial&&i>0)).join('');enlazar(c);if(enHistorial){el('resumenHistorialVisible').textContent=`Mostrando ${lista.length} de ${historial.length}`;el<HTMLButtonElement>('mostrarMasHistorial').classList.toggle('hidden',lista.length>=historial.length)}}
function mostrarModo(modo:'carga'|'visitante'|'cuenta'){el('estadoCuenta').classList.toggle('hidden',modo!=='carga');el('modoVisitante').classList.toggle('hidden',modo!=='visitante');el('modoAutenticado').classList.toggle('hidden',modo!=='cuenta')}
function ocultarCarga(){if(cargaVisible)clearTimeout(cargaVisible);el('estadoCuenta').classList.add('hidden')}
async function cargarCuenta(manual=false){const posicion=window.scrollY;if(!manual){cargaVisible=window.setTimeout(()=>mostrarModo('carga'),180)}try{const [perfil,h]=await Promise.all([api<Perfil>('/cliente/perfil'),api<Historial>('/cliente/reservas')]);ocultarCarga();autenticado=true;historialActual=h;mostrarModo('cuenta');el('consultaCodigoSiempre').classList.remove('hidden');el('accesoHeroReservas').classList.add('hidden');el('saludoCliente').textContent=`Reservas de ${perfil.nombre}`;el('resumenCuenta').textContent=h.total===1?'Tenés 1 reserva registrada.':`Tenés ${h.total} reservas registradas · ${h.anteriores.length} en el historial.`;el('ultimaActualizacionCuenta').textContent=`Actualizado ${horaActualizacion()}`;metricas(h);if(!h.proximas.length&&h.anteriores.length)tabActual='anteriores';actualizarTabs();renderLista()}catch{ocultarCarga();autenticado=false;mostrarModo('visitante');el('accesoHeroReservas').classList.remove('hidden');const guardado=localStorage.getItem('padel.solicitud.codigo')||'';const input=el<HTMLInputElement>('codigoSeguimiento');input.value=guardado;if(guardado&&uuid(guardado))await consultar(guardado,undefined,false)}finally{ocultarCarga();if(manual)requestAnimationFrame(()=>window.scrollTo({top:posicion,behavior:'auto'}))}}
function actualizarTabs(){document.querySelectorAll<HTMLButtonElement>('.bookings-tabs button').forEach(b=>{const a=b.dataset.tab===tabActual;b.classList.toggle('activo',a);b.setAttribute('aria-selected',String(a))});el('tituloVistaReservas').textContent=tabActual==='proximas'?'Próximas reservas':'Historial de reservas';el('ayudaVistaReservas').textContent=tabActual==='proximas'?'Turnos pendientes o confirmados que todavía no finalizaron.':'Reservas completadas, canceladas, expiradas o marcadas como ausencia.'}
document.querySelectorAll<HTMLButtonElement>('.bookings-tabs button').forEach(b=>b.addEventListener('click',()=>{tabActual=b.dataset.tab as typeof tabActual;actualizarTabs();renderLista()}));
el<HTMLFormElement>('formSeguimiento').addEventListener('submit',e=>{e.preventDefault();const input=el<HTMLInputElement>('codigoSeguimiento'),c=input.value.trim();if(validarCodigo(c,'errorSeguimiento',input))consultar(c,el<HTMLButtonElement>('consultarSeguimiento'))});
el<HTMLFormElement>('formSeguimientoCuenta').addEventListener('submit',e=>{e.preventDefault();const input=el<HTMLInputElement>('codigoSeguimientoCuenta'),c=input.value.trim();if(validarCodigo(c,'errorSeguimientoCuenta',input))consultar(c,el<HTMLButtonElement>('consultarSeguimientoCuenta'))});
el('abrirAccesoCliente').addEventListener('click',()=>el<HTMLButtonElement>('abrirAutenticacion').click());el('accesoHeroReservas').addEventListener('click',()=>el<HTMLButtonElement>('abrirAutenticacion').click());
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'){if(autenticado)cargarCuenta(true);else if(codigoActivo)consultar(codigoActivo,undefined,true)}});
el<HTMLSelectElement>('filtroEstadoHistorial').addEventListener('change',e=>{filtroHistorial=(e.currentTarget as HTMLSelectElement).value;limiteHistorial=8;renderLista()});el<HTMLInputElement>('buscarCanchaHistorial').addEventListener('input',e=>{busquedaHistorial=(e.currentTarget as HTMLInputElement).value.trim().toLocaleLowerCase('es');limiteHistorial=8;renderLista()});el('mostrarMasHistorial').addEventListener('click',()=>{limiteHistorial+=8;renderLista()});
(async()=>{try{complejo=await api<Complejo>('/complejo')}catch{complejo=null}await cargarCuenta()})();
