import { api } from './api';
type Posicion='DRIVE'|'REVES'|null;type Perfil={clienteId:number;nombre:string;apellido:string;documento:string;telefono:string;email:string;posicionPreferida:Posicion};
const e=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;let perfilActual:Perfil|null=null,editando=false,guardando=false;
const campos=['datosNombre','datosApellido','datosTelefono','datosEmail'] as const;
function mostrarModo(modo:'carga'|'contenido'|'sesion'){e('cargandoDatos').classList.toggle('hidden',modo!=='carga');e('contenidoDatos').classList.toggle('hidden',modo!=='contenido');e('sinSesionDatos').classList.toggle('hidden',modo!=='sesion')}
function posicion():Posicion{const x=document.querySelector<HTMLInputElement>('input[name="posicionPreferida"]:checked');return x?.value===''?null:(x?.value as Posicion)||null}
function etiquetaPosicion(p:Posicion){return p==='DRIVE'?'Drive':p==='REVES'?'Revés':'Sin preferencia'}
function normalizarTexto(v:string){return v.trim().replace(/\s+/g,' ')}
function valores(){return{nombre:normalizarTexto(e<HTMLInputElement>('datosNombre').value),apellido:normalizarTexto(e<HTMLInputElement>('datosApellido').value),telefono:e<HTMLInputElement>('datosTelefono').value.trim(),email:e<HTMLInputElement>('datosEmail').value.trim().toLowerCase(),posicionPreferida:posicion()}}
function hayCambios(){if(!perfilActual)return false;const v=valores();return v.nombre!==perfilActual.nombre||v.apellido!==perfilActual.apellido||v.telefono!==perfilActual.telefono||v.email!==perfilActual.email.toLowerCase()||v.posicionPreferida!==perfilActual.posicionPreferida}
function limpiarErrores(form:HTMLElement){form.querySelectorAll<HTMLElement>('.account-v2-field-error').forEach(x=>x.textContent='');form.querySelectorAll<HTMLInputElement>('.field-invalid').forEach(x=>{x.classList.remove('field-invalid');x.removeAttribute('aria-invalid')})}
function errorCampo(id:string,texto:string){const input=e<HTMLInputElement>(id);input.classList.add('field-invalid');input.setAttribute('aria-invalid','true');const msg=document.querySelector<HTMLElement>(`[data-error="${id}"]`);if(msg)msg.textContent=texto;input.focus({preventScroll:true});input.scrollIntoView({behavior:'smooth',block:'center'});return false}
function aviso(id:string,texto:string,tipo:'ok'|'error'){const caja=e(id);caja.textContent=texto;caja.classList.remove('hidden','ok','error');caja.classList.add(tipo)}
function ocultarAviso(id:string){const caja=e(id);caja.classList.add('hidden');caja.textContent=''}
function actualizarResumen(p:Perfil){const iniciales=((p.nombre?.[0]||'')+(p.apellido?.[0]||'')).toUpperCase()||'PR';e('inicialesCuenta').textContent=iniciales;e('nombreResumenCuenta').textContent=`${p.nombre} ${p.apellido}`;e('correoResumenCuenta').textContent=p.email;e('documentoResumenCuenta').textContent=p.documento;e('posicionResumenCuenta').textContent=etiquetaPosicion(p.posicionPreferida);e('lecturaNombre').textContent=`${p.nombre} ${p.apellido}`;e('lecturaTelefono').textContent=p.telefono;e('lecturaEmail').textContent=p.email;e('lecturaDocumento').textContent=p.documento;e('lecturaPosicion').textContent=etiquetaPosicion(p.posicionPreferida)}
function cargarCampos(p:Perfil){e<HTMLInputElement>('datosNombre').value=p.nombre;e<HTMLInputElement>('datosApellido').value=p.apellido;e('datosDocumento').textContent=p.documento;e<HTMLInputElement>('datosTelefono').value=p.telefono;e<HTMLInputElement>('datosEmail').value=p.email;const radio=document.querySelector<HTMLInputElement>(`input[name="posicionPreferida"][value="${p.posicionPreferida||''}"]`);if(radio)radio.checked=true;actualizarResumen(p);actualizarEstadoCambios()}
function actualizarEstadoCambios(){if(!perfilActual)return;const cambios=hayCambios();e<HTMLButtonElement>('guardarDatos').disabled=!cambios||guardando;e('textoCambios').textContent=cambios?'Tenés cambios sin guardar':'Sin cambios por guardar';e('textoCambios').classList.toggle('dirty',cambios);e('estadoEdicion').textContent=cambios?'Cambios sin guardar':editando?'Editando perfil':'Información actual';e('estadoEdicion').classList.toggle('dirty',cambios);const cambioEmail=e<HTMLInputElement>('datosEmail').value.trim().toLowerCase()!==perfilActual.email.toLowerCase();e('advertenciaEmail').classList.toggle('hidden',!cambioEmail)}
function alternarEdicion(activa:boolean){editando=activa;e('accionesDatos').classList.toggle('hidden',!activa);e('advertenciaEmail').classList.add('hidden');e('resumenLectura').classList.toggle('hidden',activa);e('editorDatos').classList.toggle('hidden',!activa);e('accionesDatos').classList.toggle('hidden',!activa);e<HTMLButtonElement>('editarDatos').classList.toggle('hidden',activa);e('estadoEdicion').textContent=activa?'Editando perfil':'Información actual';ocultarAviso('mensajeDatos');limpiarErrores(e('formDatos'));if(activa){cargarCampos(perfilActual!);e<HTMLInputElement>('datosNombre').focus({preventScroll:true})}else if(perfilActual)cargarCampos(perfilActual)}
async function cargar(){mostrarModo('carga');try{const p=await api<Perfil>('/cliente/perfil');perfilActual=p;cargarCampos(p);mostrarModo('contenido')}catch{mostrarModo('sesion')}}
function validarPerfil(){const v=valores();if(!v.nombre)return errorCampo('datosNombre','Ingresá tu nombre.');if(!v.apellido)return errorCampo('datosApellido','Ingresá tu apellido.');if(!/^[0-9+()\-\s]{6,30}$/.test(v.telefono))return errorCampo('datosTelefono','Ingresá un teléfono válido.');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v.email))return errorCampo('datosEmail','Ingresá un correo válido.');return true}
e<HTMLButtonElement>('editarDatos').addEventListener('click',()=>alternarEdicion(true));e<HTMLButtonElement>('descartarDatos').addEventListener('click',()=>alternarEdicion(false));
e<HTMLFormElement>('formDatos').addEventListener('submit',async ev=>{ev.preventDefault();const form=e('formDatos'),b=e<HTMLButtonElement>('guardarDatos');limpiarErrores(form);ocultarAviso('mensajeDatos');if(!validarPerfil())return;const v=valores();try{guardando=true;b.disabled=true;b.textContent='Guardando...';const p=await api<Perfil>('/cliente/perfil',{method:'PUT',body:JSON.stringify(v)});perfilActual=p;cargarCampos(p);alternarEdicion(false);aviso('mensajeDatos','Tus datos se guardaron correctamente.','ok');e('nombreUsuario').textContent=p.nombre;window.dispatchEvent(new CustomEvent('perfil-cliente-actualizado',{detail:p}))}catch(err){const mensaje=err instanceof Error?err.message:'No se pudieron guardar los datos.';if(/correo|email/i.test(mensaje)){errorCampo('datosEmail',mensaje)}else aviso('mensajeDatos',mensaje,'error')}finally{guardando=false;b.textContent='Guardar cambios';actualizarEstadoCambios()}});
document.querySelectorAll<HTMLInputElement>('#editorDatos input').forEach(input=>input.addEventListener('input',()=>{const msg=document.querySelector<HTMLElement>(`[data-error="${input.id}"]`);if(msg)msg.textContent='';input.classList.remove('field-invalid');input.removeAttribute('aria-invalid');actualizarEstadoCambios()}));document.querySelectorAll<HTMLInputElement>('input[name="posicionPreferida"]').forEach(x=>x.addEventListener('change',actualizarEstadoCambios));
const telefono=e<HTMLInputElement>('datosTelefono');telefono.addEventListener('input',()=>{const limpio=telefono.value.replace(/[^0-9+()\-\s]/g,'');if(limpio!==telefono.value)telefono.value=limpio;actualizarEstadoCambios()});
function limpiarPassword(){const form=e<HTMLFormElement>('formPassword');form.reset();e<HTMLButtonElement>('guardarPassword').disabled=true;limpiarErrores(form);ocultarAviso('mensajePassword');e('progresoPassword').className='account-v2-password-rule';e('progresoPassword').textContent='Al menos 8 caracteres';e('coincidenciaPassword').className='account-v2-password-rule';e('coincidenciaPassword').textContent='Repetí la nueva contraseña';form.querySelectorAll<HTMLInputElement>('input').forEach(x=>x.type='password');form.querySelectorAll<HTMLButtonElement>('[data-password]').forEach(x=>x.textContent='Ver')}
function alternarSeguridad(abierta:boolean){e('formPassword').classList.toggle('hidden',!abierta);e<HTMLButtonElement>('alternarSeguridad').setAttribute('aria-expanded',String(abierta));if(abierta)e<HTMLInputElement>('passwordActual').focus();else limpiarPassword()}
e<HTMLButtonElement>('alternarSeguridad').addEventListener('click',()=>alternarSeguridad(e('formPassword').classList.contains('hidden')));e<HTMLButtonElement>('cancelarPassword').addEventListener('click',()=>alternarSeguridad(false));e<HTMLButtonElement>('cancelarPasswordAccion').addEventListener('click',()=>alternarSeguridad(false));
const nueva=e<HTMLInputElement>('passwordNuevo'),repetida=e<HTMLInputElement>('passwordRepetido'),actualPassword=e<HTMLInputElement>('passwordActual'),guardarPassword=e<HTMLButtonElement>('guardarPassword');function actualizarBotonPassword(){guardarPassword.disabled=!(actualPassword.value.length>0&&nueva.value.length>=8&&nueva.value===repetida.value)}function progresoPassword(){const ok=nueva.value.length>=8,coincide=!!repetida.value&&nueva.value===repetida.value;const regla=e('progresoPassword');regla.textContent=ok?'Longitud correcta':'Al menos 8 caracteres';regla.classList.toggle('ok',ok);const match=e('coincidenciaPassword');match.textContent=!repetida.value?'Repetí la nueva contraseña':coincide?'Las contraseñas coinciden':'Las contraseñas no coinciden';match.classList.toggle('ok',coincide);match.classList.toggle('error',!!repetida.value&&!coincide);actualizarBotonPassword()}nueva.addEventListener('input',progresoPassword);repetida.addEventListener('input',progresoPassword);actualPassword.addEventListener('input',actualizarBotonPassword);
e<HTMLFormElement>('formPassword').addEventListener('submit',async ev=>{ev.preventDefault();const form=e('formPassword'),b=e<HTMLButtonElement>('guardarPassword');limpiarErrores(form);ocultarAviso('mensajePassword');const actual=e<HTMLInputElement>('passwordActual').value,nuevo=nueva.value,confirmacion=repetida.value;if(!actual){errorCampo('passwordActual','Ingresá la contraseña actual.');return}if(nuevo.length<8){errorCampo('passwordNuevo','Usá al menos 8 caracteres.');return}if(nuevo!==confirmacion){errorCampo('passwordRepetido','Las contraseñas no coinciden.');return}try{b.disabled=true;b.textContent='Actualizando...';const r=await api<{mensaje:string}>('/cliente/password',{method:'PUT',body:JSON.stringify({passwordActual:actual,passwordNuevo:nuevo,passwordRepetido:confirmacion})});limpiarPassword();aviso('mensajePassword',r.mensaje||'La contraseña se actualizó correctamente.','ok');setTimeout(()=>alternarSeguridad(false),1800)}catch(err){aviso('mensajePassword',err instanceof Error?err.message:'No se pudo actualizar la contraseña.','error')}finally{b.disabled=false;b.textContent='Actualizar contraseña'}});
document.querySelectorAll<HTMLButtonElement>('[data-password]').forEach(b=>b.addEventListener('click',()=>{const input=e<HTMLInputElement>(b.dataset.password||'');const mostrar=input.type==='password';input.type=mostrar?'text':'password';b.textContent=mostrar?'Ocultar':'Ver';b.setAttribute('aria-label',mostrar?'Ocultar contraseña':'Mostrar contraseña');input.focus()}));
window.addEventListener('beforeunload',ev=>{if(editando&&hayCambios()){ev.preventDefault();ev.returnValue=''}});document.addEventListener('click',ev=>{const a=(ev.target as HTMLElement).closest('a');if(a&&editando&&hayCambios()&&!window.confirm('Tenés cambios sin guardar. ¿Querés salir igualmente?'))ev.preventDefault()},true);
e('abrirSesionDatos').addEventListener('click',()=>e<HTMLButtonElement>('abrirAutenticacion').click());cargar();
