import { api } from './api';
type Posicion='DRIVE'|'REVES'|null;type Perfil={clienteId:number;nombre:string;apellido:string;documento:string;telefono:string;email:string;posicionPreferida:Posicion};
const e=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;let perfilActual:Perfil|null=null;
function limpiarErrores(form:HTMLElement){form.querySelectorAll<HTMLElement>('.account-field-error').forEach(x=>x.textContent='');form.querySelectorAll('.field-invalid').forEach(x=>x.classList.remove('field-invalid'))}
function errorCampo(id:string,texto:string):never{const input=e<HTMLInputElement>(id);input.classList.add('field-invalid');const msg=document.querySelector<HTMLElement>(`[data-error="${id}"]`);if(msg)msg.textContent=texto;input.focus();throw new Error(texto)}
function aviso(id:string,texto:string,tipo:'ok'|'error'){const caja=e(id);caja.textContent=texto;caja.classList.remove('hidden','ok','error');caja.classList.add(tipo)}
function ocultarAviso(id:string){const caja=e(id);caja.classList.add('hidden');caja.textContent=''}
function posicion():Posicion{const x=document.querySelector<HTMLInputElement>('input[name="posicionPreferida"]:checked');return x?.value===''?null:(x?.value as Posicion)||null}
function etiquetaPosicion(p:Posicion){return p==='DRIVE'?'Drive':p==='REVES'?'Revés':'Sin preferencia'}
function actualizarResumen(p:Perfil){const iniciales=((p.nombre?.[0]||'')+(p.apellido?.[0]||'')).toUpperCase()||'PR';e('inicialesCuenta').textContent=iniciales;e('nombreResumenCuenta').textContent=`${p.nombre} ${p.apellido}`;e('correoResumenCuenta').textContent=p.email;e('documentoResumenCuenta').textContent=p.documento;e('posicionResumenCuenta').textContent=etiquetaPosicion(p.posicionPreferida)}
function cargarCampos(p:Perfil){e<HTMLInputElement>('datosNombre').value=p.nombre;e<HTMLInputElement>('datosApellido').value=p.apellido;e<HTMLInputElement>('datosDocumento').value=p.documento;e<HTMLInputElement>('datosTelefono').value=p.telefono;e<HTMLInputElement>('datosEmail').value=p.email;const radio=document.querySelector<HTMLInputElement>(`input[name="posicionPreferida"][value="${p.posicionPreferida||''}"]`);if(radio)radio.checked=true;actualizarResumen(p)}
async function cargar(){try{const p=await api<Perfil>('/cliente/perfil');perfilActual=p;cargarCampos(p);e('cargandoDatos').classList.add('hidden');e('contenidoDatos').classList.remove('hidden')}catch{e('cargandoDatos').classList.add('hidden');e('sinSesionDatos').classList.remove('hidden')}}
e<HTMLFormElement>('formDatos').addEventListener('submit',async ev=>{ev.preventDefault();const form=e('formDatos'),b=e<HTMLButtonElement>('guardarDatos');limpiarErrores(form);ocultarAviso('mensajeDatos');const nombre=e<HTMLInputElement>('datosNombre').value.trim(),apellido=e<HTMLInputElement>('datosApellido').value.trim(),telefono=e<HTMLInputElement>('datosTelefono').value.trim(),email=e<HTMLInputElement>('datosEmail').value.trim().toLowerCase();try{if(!nombre)errorCampo('datosNombre','Ingresá tu nombre.');if(!apellido)errorCampo('datosApellido','Ingresá tu apellido.');if(!/^[0-9+()\-\s]{6,30}$/.test(telefono))errorCampo('datosTelefono','Ingresá un teléfono válido.');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))errorCampo('datosEmail','Ingresá un correo válido.');b.disabled=true;b.textContent='Guardando...';const p=await api<Perfil>('/cliente/perfil',{method:'PUT',body:JSON.stringify({nombre,apellido,telefono,email,posicionPreferida:posicion()})});perfilActual=p;cargarCampos(p);aviso('mensajeDatos','Tus datos se guardaron correctamente.','ok');e('nombreUsuario').textContent=p.nombre;window.dispatchEvent(new CustomEvent('perfil-cliente-actualizado',{detail:p}))}catch(err){aviso('mensajeDatos',err instanceof Error?err.message:'No se pudieron guardar los datos.','error')}finally{b.disabled=false;b.textContent='Guardar cambios'}});
e<HTMLFormElement>('formPassword').addEventListener('submit',async ev=>{ev.preventDefault();const form=e('formPassword'),b=e<HTMLButtonElement>('guardarPassword');limpiarErrores(form);ocultarAviso('mensajePassword');const actual=e<HTMLInputElement>('passwordActual').value,nueva=e<HTMLInputElement>('passwordNuevo').value,repetida=e<HTMLInputElement>('passwordRepetido').value;try{if(!actual)errorCampo('passwordActual','Ingresá la contraseña actual.');if(nueva.length<8)errorCampo('passwordNuevo','Usá al menos 8 caracteres.');if(nueva!==repetida)errorCampo('passwordRepetido','Las contraseñas no coinciden.');b.disabled=true;b.textContent='Actualizando...';const r=await api<{mensaje:string}>('/cliente/password',{method:'PUT',body:JSON.stringify({passwordActual:actual,passwordNuevo:nueva,passwordRepetido:repetida})});form.querySelector<HTMLFormElement>('form')?.reset();e<HTMLFormElement>('formPassword').reset();aviso('mensajePassword',r.mensaje||'La contraseña se actualizó correctamente.','ok')}catch(err){aviso('mensajePassword',err instanceof Error?err.message:'No se pudo actualizar la contraseña.','error')}finally{b.disabled=false;b.textContent='Actualizar contraseña'}});
const telefono=e<HTMLInputElement>('datosTelefono'),email=e<HTMLInputElement>('datosEmail');
telefono.addEventListener('input',()=>{const limpio=telefono.value.replace(/[^0-9+()\-\s]/g,'');if(limpio!==telefono.value)telefono.value=limpio;const msg=document.querySelector<HTMLElement>('[data-error="datosTelefono"]');if(msg&&/^[0-9+()\-\s]{6,30}$/.test(telefono.value.trim())){msg.textContent='';telefono.classList.remove('field-invalid')}});
telefono.addEventListener('blur',()=>{const valor=telefono.value.trim(),msg=document.querySelector<HTMLElement>('[data-error="datosTelefono"]');if(valor&&!/^[0-9+()\-\s]{6,30}$/.test(valor)){telefono.classList.add('field-invalid');if(msg)msg.textContent='Ingresá un teléfono válido de entre 6 y 30 caracteres.'}});
email.addEventListener('input',()=>{const msg=document.querySelector<HTMLElement>('[data-error="datosEmail"]');if(msg&&/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.value.trim())){msg.textContent='';email.classList.remove('field-invalid')}});
email.addEventListener('blur',()=>{const valor=email.value.trim(),msg=document.querySelector<HTMLElement>('[data-error="datosEmail"]');if(valor&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(valor)){email.classList.add('field-invalid');if(msg)msg.textContent='Usá un formato como nombre@dominio.com.'}});
document.querySelectorAll<HTMLButtonElement>('[data-password]').forEach(b=>b.addEventListener('click',()=>{const input=e<HTMLInputElement>(b.dataset.password||'');const mostrar=input.type==='password';input.type=mostrar?'text':'password';b.textContent=mostrar?'Ocultar':'Ver';b.setAttribute('aria-label',mostrar?'Ocultar contraseña':'Mostrar contraseña');input.focus()}));
e('abrirSesionDatos').addEventListener('click',()=>e<HTMLButtonElement>('abrirAutenticacion').click());
cargar();