import { api } from './api';
type Posicion='DRIVE'|'REVES'|null;
type Perfil={clienteId:number;nombre:string;apellido:string;documento:string;telefono:string;email:string;posicionPreferida:Posicion};
const e=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
function aviso(id:string,texto:string,tipo:'ok'|'error'){const caja=e(id);caja.textContent=texto;caja.classList.remove('hidden','border-emerald-500/30','bg-emerald-500/10','text-emerald-200','border-rose-500/30','bg-rose-500/10','text-rose-200');caja.classList.add(...(tipo==='ok'?['border','border-emerald-500/30','bg-emerald-500/10','text-emerald-200']:['border','border-rose-500/30','bg-rose-500/10','text-rose-200']));}
function posicion():Posicion{const seleccionado=document.querySelector<HTMLInputElement>('input[name="posicionPreferida"]:checked');return seleccionado?.value===''?null:(seleccionado?.value as Posicion)||null;}
async function cargar(){try{const p=await api<Perfil>('/cliente/perfil');e<HTMLInputElement>('datosNombre').value=p.nombre;e<HTMLInputElement>('datosApellido').value=p.apellido;e<HTMLInputElement>('datosDocumento').value=p.documento;e<HTMLInputElement>('datosTelefono').value=p.telefono;e<HTMLInputElement>('datosEmail').value=p.email;const radio=document.querySelector<HTMLInputElement>(`input[name="posicionPreferida"][value="${p.posicionPreferida||''}"]`);if(radio)radio.checked=true;e('cargandoDatos').classList.add('hidden');e('contenidoDatos').classList.remove('hidden');}catch{e('cargandoDatos').classList.add('hidden');e('sinSesionDatos').classList.remove('hidden');}}
e<HTMLFormElement>('formDatos').addEventListener('submit',async evento=>{evento.preventDefault();const b=e<HTMLButtonElement>('guardarDatos');const nombre=e<HTMLInputElement>('datosNombre').value.trim();const apellido=e<HTMLInputElement>('datosApellido').value.trim();const telefono=e<HTMLInputElement>('datosTelefono').value.trim();const email=e<HTMLInputElement>('datosEmail').value.trim();try{if(!nombre)throw new Error('El nombre es obligatorio.');if(!apellido)throw new Error('El apellido es obligatorio.');if(!/^[0-9+()\-\s]{6,30}$/.test(telefono))throw new Error('El teléfono contiene caracteres no válidos.');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw new Error('El correo electrónico no tiene un formato válido.');b.disabled=true;b.textContent='Guardando...';const p=await api<Perfil>('/cliente/perfil',{method:'PUT',body:JSON.stringify({nombre,apellido,telefono,email,posicionPreferida:posicion()})});aviso('mensajeDatos',`Datos guardados. Posición: ${p.posicionPreferida==='DRIVE'?'Drive':p.posicionPreferida==='REVES'?'Revés':'Sin preferencia'}.`,'ok');window.dispatchEvent(new CustomEvent('perfil-cliente-actualizado',{detail:p}));}catch(err){aviso('mensajeDatos',err instanceof Error?err.message:'No se pudieron guardar los datos.','error');}finally{b.disabled=false;b.textContent='Guardar cambios';}});
e<HTMLFormElement>('formPassword').addEventListener('submit',async evento=>{evento.preventDefault();const b=e<HTMLButtonElement>('guardarPassword');const passwordActual=e<HTMLInputElement>('passwordActual').value;const passwordNuevo=e<HTMLInputElement>('passwordNuevo').value;const passwordRepetido=e<HTMLInputElement>('passwordRepetido').value;try{if(!passwordActual)throw new Error('Ingresá la contraseña actual.');if(passwordNuevo.length<8)throw new Error('La contraseña nueva debe tener al menos 8 caracteres.');if(passwordNuevo!==passwordRepetido)throw new Error('Las contraseñas nuevas no coinciden.');b.disabled=true;b.textContent='Actualizando...';const respuesta=await api<{mensaje:string}>('/cliente/password',{method:'PUT',body:JSON.stringify({passwordActual,passwordNuevo,passwordRepetido})});aviso('mensajePassword',respuesta.mensaje||'Contraseña actualizada correctamente.','ok');e<HTMLFormElement>('formPassword').reset();}catch(err){aviso('mensajePassword',err instanceof Error?err.message:'No se pudo actualizar la contraseña.','error');}finally{b.disabled=false;b.textContent='Actualizar contraseña';}});
cargar();
