const API="http://localhost:8080/api/publica";
const state={complex:null,courts:[],court:null,date:null,time:null,availability:null,expires:null,timer:null};
const $=id=>document.getElementById(id);
const money=(v,c="ARS")=>new Intl.NumberFormat("es-AR",{style:"currency",currency:c}).format(Number(v||0));
const dateAr=v=>new Intl.DateTimeFormat("es-AR",{dateStyle:"full"}).format(new Date(v+"T12:00:00"));
const escapeHtml=s=>String(s??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));

async function api(path,options={}){const r=await fetch(API+path,{headers:{"Content-Type":"application/json",...(options.headers||{})},...options});let data;try{data=await r.json()}catch{data={mensaje:"Respuesta inválida del servidor."}}if(!r.ok)throw new Error(data.mensaje||"No se pudo completar la operación.");return data}
function message(text,type="error"){const el=$("globalMessage");el.textContent=text;el.classList.toggle("hidden",!text);el.style.background=type==="success"?"#17372c":"#3c252a"}
function showStep(n){document.querySelectorAll(".step-panel").forEach((p,i)=>p.classList.toggle("hidden",i!==n-1));document.querySelectorAll(".step").forEach((s,i)=>s.classList.toggle("active",i<=n-1));message("");window.location.hash="reservar"}

async function init(){const today=new Date();today.setMinutes(today.getMinutes()-today.getTimezoneOffset());$("dateInput").min=today.toISOString().slice(0,10);$("dateInput").value=new Date(today.getTime()+86400000).toISOString().slice(0,10);try{const [complex,courts]=await Promise.all([api("/complejo"),api("/canchas")]);state.complex=complex;state.courts=courts;document.documentElement.style.setProperty("--primary",complex.colorPrincipal||"#486B86");$("brandName").textContent=complex.nombreComercial;$("footerName").textContent=complex.nombreComercial;$("footerContact").textContent=[complex.direccion,complex.whatsapp].filter(Boolean).join(" · ");document.title=`Reservas | ${complex.nombreComercial}`;const select=$("courtSelect");select.innerHTML='<option value="">Seleccionar cancha</option>'+courts.map(c=>`<option value="${c.id}">${escapeHtml(c.nombre)}</option>`).join("");$("apiStatus").textContent="Disponibilidad online";select.addEventListener("change",courtChanged)}catch(e){$("apiStatus").textContent="Servicio no disponible";$("apiStatus").classList.add("offline");message("No pudimos conectarnos con el sistema de reservas. Verificá que la aplicación administrativa esté abierta.")}}
function courtChanged(){state.court=state.courts.find(c=>String(c.id)===$("courtSelect").value)||null;const e=$("courtSummary");if(!state.court){e.innerHTML="<p>Seleccioná una cancha para ver sus características.</p>";return}const c=state.court;e.innerHTML=`<p><strong>${escapeHtml(c.nombre)}</strong> · ${c.duracionMinutos} minutos · ${money(c.precio,state.complex.moneda)} · Seña ${money(c.importeSenia,state.complex.moneda)}</p>`}

$("loadAvailability").addEventListener("click",async()=>{state.date=$("dateInput").value;if(!state.court||!state.date){message("Seleccioná una cancha y una fecha.");return}const b=$("loadAvailability");b.disabled=true;b.textContent="Consultando...";try{state.availability=await api(`/disponibilidad?canchaId=${state.court.id}&fecha=${state.date}`);renderTimes();showStep(2)}catch(e){message(e.message)}finally{b.disabled=false;b.textContent="Consultar horarios"}});
function renderTimes(){const times=state.availability.horarios||[];$("availabilityTitle").textContent=`${state.court.nombre} · ${dateAr(state.date)}`;$("timeGrid").innerHTML=times.map(t=>`<button class="time-button" data-time="${t.horaInicio}">${t.horaInicio.slice(0,5)} a ${t.horaFin.slice(0,5)}</button>`).join("");$("noTimes").classList.toggle("hidden",times.length>0);document.querySelectorAll(".time-button").forEach(b=>b.addEventListener("click",()=>selectTime(b.dataset.time)))}
function selectTime(time){state.time=state.availability.horarios.find(t=>t.horaInicio===time);$("selectionSummary").innerHTML=`<strong>${escapeHtml(state.court.nombre)}</strong><br>${dateAr(state.date)} · ${state.time.horaInicio.slice(0,5)} a ${state.time.horaFin.slice(0,5)}<br>Precio: ${money(state.time.precio,state.complex.moneda)} · Seña: ${money(state.time.importeSenia,state.complex.moneda)}`;showStep(3)}
document.querySelectorAll("[data-back]").forEach(b=>b.addEventListener("click",()=>showStep(Number(b.dataset.back))));

$("requestForm").addEventListener("submit",async e=>{e.preventDefault();if(!state.court||!state.date||!state.time)return message("La selección del turno está incompleta.");const body={canchaId:state.court.id,fecha:state.date,horaInicio:state.time.horaInicio,cantidadJugadores:Number($("players").value),cliente:{nombre:$("firstName").value.trim(),apellido:$("lastName").value.trim(),documento:$("document").value.trim(),telefono:$("phone").value.trim(),email:$("email").value.trim()||null},comentarios:$("comments").value.trim()||null};const b=$("submitRequest");b.disabled=true;b.textContent="Creando solicitud...";try{const r=await api("/solicitudes",{method:"POST",body:JSON.stringify(body)});renderConfirmation(r);showStep(4)}catch(err){message(err.message)}finally{b.disabled=false;b.textContent="Solicitar reserva"}});
function renderConfirmation(r){state.expires=new Date(r.vencimiento);$("confirmationSummary").innerHTML=`<strong>Solicitud #${r.solicitudId}</strong><br>${escapeHtml(r.cancha)} · ${dateAr(r.fecha)} · ${r.horaInicio.slice(0,5)} a ${r.horaFin.slice(0,5)}<br>Precio: ${money(r.precioTotal,r.moneda)}<br><strong>Seña a acreditar: ${money(r.importeSenia,r.moneda)}</strong>`;$("paymentInstructions").textContent=["La solicitud ya aparece en el sistema del complejo.",state.complex.whatsapp?`Para informar el pago, comunicate por WhatsApp al ${state.complex.whatsapp}.`:"El complejo te indicará cómo informar el pago."].join(" ");startCountdown()}
function startCountdown(){clearInterval(state.timer);const update=()=>{const ms=state.expires-Date.now();if(ms<=0){$("countdown").textContent="EXPIRADA";clearInterval(state.timer);return}const min=Math.floor(ms/60000),sec=Math.floor((ms%60000)/1000);$("countdown").textContent=`${String(min).padStart(2,"0")}:${String(sec).padStart(2,"0")}`};update();state.timer=setInterval(update,1000)}
$("newRequest").addEventListener("click",()=>{clearInterval(state.timer);state.date=null;state.time=null;state.availability=null;$("requestForm").reset();$("courtSelect").value="";courtChanged();showStep(1)});
init();
